#pragma once

#define _np1_x12AdapterRegisterVideoMemoryBudgetChangeNotificationEvent pAdapter
#define _np2_x12AdapterRegisterVideoMemoryBudgetChangeNotificationEvent hEvent
#define _np3_x12AdapterRegisterVideoMemoryBudgetChangeNotificationEvent outdwCookie
#define _np4_x12AdapterRegisterVideoMemoryBudgetChangeNotificationEvent optionalFile
#define _np5_x12AdapterRegisterVideoMemoryBudgetChangeNotificationEvent optionalLine

#define _np1_x12AdapterUnregisterVideoMemoryBudgetChangeNotification pAdapter
#define _np2_x12AdapterUnregisterVideoMemoryBudgetChangeNotification dwCookie
#define _np3_x12AdapterUnregisterVideoMemoryBudgetChangeNotification optionalFile
#define _np4_x12AdapterUnregisterVideoMemoryBudgetChangeNotification optionalLine

#define _np1_x12AdapterQueryVideoMemoryInfo pAdapter
#define _np2_x12AdapterQueryVideoMemoryInfo NodeIndex
#define _np3_x12AdapterQueryVideoMemoryInfo MemorySegmentGroup
#define _np4_x12AdapterQueryVideoMemoryInfo pVideoMemoryInfo
#define _np5_x12AdapterQueryVideoMemoryInfo optionalFile
#define _np6_x12AdapterQueryVideoMemoryInfo optionalLine

#define _np1_x12AdapterSetVideoMemoryReservation pAdapter
#define _np2_x12AdapterSetVideoMemoryReservation NodeIndex
#define _np3_x12AdapterSetVideoMemoryReservation MemorySegmentGroup
#define _np4_x12AdapterSetVideoMemoryReservation Reservation
#define _np5_x12AdapterSetVideoMemoryReservation optionalFile
#define _np6_x12AdapterSetVideoMemoryReservation optionalLine

#define _np1_x12DeviceCreateHeap pDevice
#define _np2_x12DeviceCreateHeap pDesc
#define _np3_x12DeviceCreateHeap outpHeap
#define _np4_x12DeviceCreateHeap optionalFile
#define _np5_x12DeviceCreateHeap optionalLine

#define _np1_x12DeviceGetResourceAllocationInfo pDevice
#define _np2_x12DeviceGetResourceAllocationInfo visibleMask
#define _np3_x12DeviceGetResourceAllocationInfo numResourceDescs
#define _np4_x12DeviceGetResourceAllocationInfo pResourceDescs
#define _np5_x12DeviceGetResourceAllocationInfo outResourceAllocationInfo
#define _np6_x12DeviceGetResourceAllocationInfo optionalFile
#define _np7_x12DeviceGetResourceAllocationInfo optionalLine

#define _np1_x12DeviceCreatePlacedResource pDevice
#define _np2_x12DeviceCreatePlacedResource pHeap
#define _np3_x12DeviceCreatePlacedResource HeapOffset
#define _np4_x12DeviceCreatePlacedResource pDesc
#define _np5_x12DeviceCreatePlacedResource InitialState
#define _np6_x12DeviceCreatePlacedResource pOptimizedClearValue
#define _np7_x12DeviceCreatePlacedResource outpResource
#define _np8_x12DeviceCreatePlacedResource optionalFile
#define _np9_x12DeviceCreatePlacedResource optionalLine

#define _np1_x12DeviceCreateCommittedResource pDevice
#define _np2_x12DeviceCreateCommittedResource pHeapProperties
#define _np3_x12DeviceCreateCommittedResource HeapFlags
#define _np4_x12DeviceCreateCommittedResource pDesc
#define _np5_x12DeviceCreateCommittedResource InitialResourceState
#define _np6_x12DeviceCreateCommittedResource pOptimizedClearValue
#define _np7_x12DeviceCreateCommittedResource outpResource
#define _np8_x12DeviceCreateCommittedResource optionalFile
#define _np9_x12DeviceCreateCommittedResource optionalLine

#define _np1_x12ResourceMap pResource
#define _np2_x12ResourceMap Subresource
#define _np3_x12ResourceMap pReadRange
#define _np4_x12ResourceMap outpData
#define _np5_x12ResourceMap optionalFile
#define _np6_x12ResourceMap optionalLine

#define _np1_x12ResourceUnmap pResource
#define _np2_x12ResourceUnmap Subresource
#define _np3_x12ResourceUnmap pWrittenRange
#define _np4_x12ResourceUnmap optionalFile
#define _np5_x12ResourceUnmap optionalLine

#define _np1_x12DeviceCreateDescriptorHeap pDevice
#define _np2_x12DeviceCreateDescriptorHeap pDescriptorHeapDesc
#define _np3_x12DeviceCreateDescriptorHeap outpHeap
#define _np4_x12DeviceCreateDescriptorHeap optionalFile
#define _np5_x12DeviceCreateDescriptorHeap optionalLine

#define _np1_x12DescriptorHeapGetCPUDescriptorHandleForHeapStart pDescriptorHeap
#define _np2_x12DescriptorHeapGetCPUDescriptorHandleForHeapStart pCpuDescriptorHandle

#define _np1_x12DeviceCopyDescriptors pDevice
#define _np2_x12DeviceCopyDescriptors NumDestDescriptorRanges
#define _np3_x12DeviceCopyDescriptors pDestDescriptorRangeStarts
#define _np4_x12DeviceCopyDescriptors pDestDescriptorRangeSizes
#define _np5_x12DeviceCopyDescriptors NumSrcDescriptorRanges
#define _np6_x12DeviceCopyDescriptors pSrcDescriptorRangeStarts
#define _np7_x12DeviceCopyDescriptors pSrcDescriptorRangeSizes
#define _np8_x12DeviceCopyDescriptors DescriptorHeapsType
#define _np9_x12DeviceCopyDescriptors optionalFile
#define _np10_x12DeviceCopyDescriptors optionalLine

#define _np1_x12DescriptorHeapGetGPUDescriptorHandleForHeapStart pDescriptorHeap
#define _np2_x12DescriptorHeapGetGPUDescriptorHandleForHeapStart pGpuDescriptorHandle

#define _np1_x12DeviceSetResidencyPriority pDevice
#define _np2_x12DeviceSetResidencyPriority NumObjects
#define _np3_x12DeviceSetResidencyPriority ppObjects
#define _np4_x12DeviceSetResidencyPriority pPriorities
#define _np5_x12DeviceSetResidencyPriority optionalFile
#define _np6_x12DeviceSetResidencyPriority optionalLine

#define _np1_x12DeviceEvict pDevice
#define _np2_x12DeviceEvict NumObjects
#define _np3_x12DeviceEvict ppObjects
#define _np4_x12DeviceEvict optionalFile
#define _np5_x12DeviceEvict optionalLine

#define _np1_x12DeviceMakeResident pDevice
#define _np2_x12DeviceMakeResident NumObjects
#define _np3_x12DeviceMakeResident ppObjects
#define _np4_x12DeviceMakeResident optionalFile
#define _np5_x12DeviceMakeResident optionalLine

#define _np1_x12DeviceEnqueueMakeResident pDevice
#define _np2_x12DeviceEnqueueMakeResident Flags
#define _np3_x12DeviceEnqueueMakeResident NumObjects
#define _np4_x12DeviceEnqueueMakeResident ppObjects
#define _np5_x12DeviceEnqueueMakeResident pFenceToSignal
#define _np6_x12DeviceEnqueueMakeResident FenceValueToSignal
#define _np7_x12DeviceEnqueueMakeResident optionalFile
#define _np8_x12DeviceEnqueueMakeResident optionalLine

#define _np1_x12DebugEnable optionalFile
#define _np2_x12DebugEnable optionalLine

#define _np1_x12DebugReport debugContext
#define _np2_x12DebugReport optionalFile
#define _np3_x12DebugReport optionalLine

#define _np1_x12CreateFactory2 Flags
#define _np2_x12CreateFactory2 outpFactory
#define _np3_x12CreateFactory2 optionalFile
#define _np4_x12CreateFactory2 optionalLine

#define _np1_x12FactoryEnumAdapters1 pFactory
#define _np2_x12FactoryEnumAdapters1 Adapter
#define _np3_x12FactoryEnumAdapters1 outpAdapter
#define _np4_x12FactoryEnumAdapters1 optionalFile
#define _np5_x12FactoryEnumAdapters1 optionalLine

#define _np1_x12CreateDevice pAdapter
#define _np2_x12CreateDevice MinimumFeatureLevel
#define _np3_x12CreateDevice outpDevice
#define _np4_x12CreateDevice optionalFile
#define _np5_x12CreateDevice optionalLine

#define _np1_x12DeviceCreateUnorderedAccessView pDevice
#define _np2_x12DeviceCreateUnorderedAccessView pResource
#define _np3_x12DeviceCreateUnorderedAccessView pCounterResource
#define _np4_x12DeviceCreateUnorderedAccessView pDesc
#define _np5_x12DeviceCreateUnorderedAccessView DestDescriptor
#define _np6_x12DeviceCreateUnorderedAccessView optionalFile
#define _np7_x12DeviceCreateUnorderedAccessView optionalLine

#define _np1_x12DeviceCreateShaderResourceView pDevice
#define _np2_x12DeviceCreateShaderResourceView pResource
#define _np3_x12DeviceCreateShaderResourceView pDesc
#define _np4_x12DeviceCreateShaderResourceView DestDescriptor
#define _np5_x12DeviceCreateShaderResourceView optionalFile
#define _np6_x12DeviceCreateShaderResourceView optionalLine

#define _np1_x12DeviceCreateConstantBufferView pDevice
#define _np2_x12DeviceCreateConstantBufferView pDesc
#define _np3_x12DeviceCreateConstantBufferView DestDescriptor
#define _np4_x12DeviceCreateConstantBufferView optionalFile
#define _np5_x12DeviceCreateConstantBufferView optionalLine

#define _np1_x12DeviceCreateSampler pDevice
#define _np2_x12DeviceCreateSampler pDesc
#define _np3_x12DeviceCreateSampler DestDescriptor
#define _np4_x12DeviceCreateSampler optionalFile
#define _np5_x12DeviceCreateSampler optionalLine

#define _np1_x12DeviceCreateRenderTargetView pDevice
#define _np2_x12DeviceCreateRenderTargetView pResource
#define _np3_x12DeviceCreateRenderTargetView pDesc
#define _np4_x12DeviceCreateRenderTargetView DestDescriptor
#define _np5_x12DeviceCreateRenderTargetView optionalFile
#define _np6_x12DeviceCreateRenderTargetView optionalLine

#define _np1_x12DeviceCreateDepthStencilView pDevice
#define _np2_x12DeviceCreateDepthStencilView pResource
#define _np3_x12DeviceCreateDepthStencilView pDesc
#define _np4_x12DeviceCreateDepthStencilView DestDescriptor
#define _np5_x12DeviceCreateDepthStencilView optionalFile
#define _np6_x12DeviceCreateDepthStencilView optionalLine

#define _np1_x12SerializeRootSignature pRootSignature
#define _np2_x12SerializeRootSignature Version
#define _np3_x12SerializeRootSignature outpBlob
#define _np4_x12SerializeRootSignature outpErrorBlob
#define _np5_x12SerializeRootSignature optionalFile
#define _np6_x12SerializeRootSignature optionalLine

#define _np1_x12DeviceCreateRootSignature pDevice
#define _np2_x12DeviceCreateRootSignature nodeMask
#define _np3_x12DeviceCreateRootSignature pBlobWithRootSignature
#define _np4_x12DeviceCreateRootSignature blobLengthInBytes
#define _np5_x12DeviceCreateRootSignature outpRootSignature
#define _np6_x12DeviceCreateRootSignature optionalFile
#define _np7_x12DeviceCreateRootSignature optionalLine

#define _np1_x12DeviceCreateGraphicsPipelineState pDevice
#define _np2_x12DeviceCreateGraphicsPipelineState pDesc
#define _np3_x12DeviceCreateGraphicsPipelineState outpPipelineState
#define _np4_x12DeviceCreateGraphicsPipelineState optionalFile
#define _np5_x12DeviceCreateGraphicsPipelineState optionalLine

#define _np1_x12DeviceCreateComputePipelineState pDevice
#define _np2_x12DeviceCreateComputePipelineState pDesc
#define _np3_x12DeviceCreateComputePipelineState outpPipelineState
#define _np4_x12DeviceCreateComputePipelineState optionalFile
#define _np5_x12DeviceCreateComputePipelineState optionalLine

#define _np1_x12DeviceCreateFence pDevice
#define _np2_x12DeviceCreateFence InitialValue
#define _np3_x12DeviceCreateFence Flags
#define _np4_x12DeviceCreateFence outpFence
#define _np5_x12DeviceCreateFence optionalFile
#define _np6_x12DeviceCreateFence optionalLine

#define _np1_x12DeviceCreateCommandQueue pDevice
#define _np2_x12DeviceCreateCommandQueue pDesc
#define _np3_x12DeviceCreateCommandQueue outpCommandQueue
#define _np4_x12DeviceCreateCommandQueue optionalFile
#define _np5_x12DeviceCreateCommandQueue optionalLine

#define _np1_x12DeviceCreateCommandAllocator pDevice
#define _np2_x12DeviceCreateCommandAllocator type
#define _np3_x12DeviceCreateCommandAllocator outpCommandAllocator
#define _np4_x12DeviceCreateCommandAllocator optionalFile
#define _np5_x12DeviceCreateCommandAllocator optionalLine

#define _np1_x12DeviceCreateCommandList pDevice
#define _np2_x12DeviceCreateCommandList nodeMask
#define _np3_x12DeviceCreateCommandList type
#define _np4_x12DeviceCreateCommandList pCommandAllocator
#define _np5_x12DeviceCreateCommandList pInitialState
#define _np6_x12DeviceCreateCommandList outpCommandList
#define _np7_x12DeviceCreateCommandList optionalFile
#define _np8_x12DeviceCreateCommandList optionalLine

#define _np1_x12ResourceGetGPUVirtualAddress pResource

#define _np1_x12PipelineStateGetCachedBlob pPipelineState
#define _np2_x12PipelineStateGetCachedBlob outpBlob
#define _np3_x12PipelineStateGetCachedBlob optionalFile
#define _np4_x12PipelineStateGetCachedBlob optionalLine

#define _np1_x12BlobGetBufferPointer pBlob

#define _np1_x12BlobGetBufferSize pBlob

#define _np1_x12CreateRootSignatureDeserializer pSrcData
#define _np2_x12CreateRootSignatureDeserializer SrcDataSizeInBytes
#define _np3_x12CreateRootSignatureDeserializer outpRootSignatureDeserializer
#define _np4_x12CreateRootSignatureDeserializer optionalFile
#define _np5_x12CreateRootSignatureDeserializer optionalLine

#define _np1_x12RootSignatureDeserializerGetRootSignatureDesc pRootSignatureDeserializer
#define _np2_x12RootSignatureDeserializerGetRootSignatureDesc optionalFile
#define _np3_x12RootSignatureDeserializerGetRootSignatureDesc optionalLine

#define _np1_x12FenceGetCompletedValue pFence
#define _np2_x12FenceGetCompletedValue optionalFile
#define _np3_x12FenceGetCompletedValue optionalLine

#define _np1_x12FenceSetEventOnCompletion pFence
#define _np2_x12FenceSetEventOnCompletion Value
#define _np3_x12FenceSetEventOnCompletion hEvent
#define _np4_x12FenceSetEventOnCompletion optionalFile
#define _np5_x12FenceSetEventOnCompletion optionalLine

#define _np1_x12DeviceSetEventOnMultipleFenceCompletion pDevice
#define _np2_x12DeviceSetEventOnMultipleFenceCompletion ppFences
#define _np3_x12DeviceSetEventOnMultipleFenceCompletion pFenceValues
#define _np4_x12DeviceSetEventOnMultipleFenceCompletion NumFences
#define _np5_x12DeviceSetEventOnMultipleFenceCompletion Flag
#define _np6_x12DeviceSetEventOnMultipleFenceCompletion hEvent
#define _np7_x12DeviceSetEventOnMultipleFenceCompletion optionalFile
#define _np8_x12DeviceSetEventOnMultipleFenceCompletion optionalLine

#define _np1_x12FenceSignal pFence
#define _np2_x12FenceSignal Value
#define _np3_x12FenceSignal optionalFile
#define _np4_x12FenceSignal optionalLine

#define _np1_x12CommandAllocatorReset pCommandAllocator
#define _np2_x12CommandAllocatorReset optionalFile
#define _np3_x12CommandAllocatorReset optionalLine

#define _np1_x12CommandListReset pCommandList
#define _np2_x12CommandListReset pAllocator
#define _np3_x12CommandListReset pInitialState
#define _np4_x12CommandListReset optionalFile
#define _np5_x12CommandListReset optionalLine

#define _np1_x12CommandListClose pCommandList
#define _np2_x12CommandListClose optionalFile
#define _np3_x12CommandListClose optionalLine

#define _np1_x12CommandListCopyBufferRegion pCommandList
#define _np2_x12CommandListCopyBufferRegion pDstBuffer
#define _np3_x12CommandListCopyBufferRegion DstOffset
#define _np4_x12CommandListCopyBufferRegion pSrcBuffer
#define _np5_x12CommandListCopyBufferRegion SrcOffset
#define _np6_x12CommandListCopyBufferRegion NumBytes

#define _np1_x12CommandListClearUnorderedAccessViewUint pCommandList
#define _np2_x12CommandListClearUnorderedAccessViewUint ViewGPUHandleInCurrentHeap
#define _np3_x12CommandListClearUnorderedAccessViewUint ViewCPUHandle
#define _np4_x12CommandListClearUnorderedAccessViewUint pResource
#define _np5_x12CommandListClearUnorderedAccessViewUint Values[4]
#define _np6_x12CommandListClearUnorderedAccessViewUint NumRects
#define _np7_x12CommandListClearUnorderedAccessViewUint pRects

#define _np1_x12CommandListClearUnorderedAccessViewFloat pCommandList
#define _np2_x12CommandListClearUnorderedAccessViewFloat ViewGPUHandleInCurrentHeap
#define _np3_x12CommandListClearUnorderedAccessViewFloat ViewCPUHandle
#define _np4_x12CommandListClearUnorderedAccessViewFloat pResource
#define _np5_x12CommandListClearUnorderedAccessViewFloat Values[4]
#define _np6_x12CommandListClearUnorderedAccessViewFloat NumRects
#define _np7_x12CommandListClearUnorderedAccessViewFloat pRects

#define _np1_x12CommandListDrawInstanced pCommandList
#define _np2_x12CommandListDrawInstanced VertexCountPerInstance
#define _np3_x12CommandListDrawInstanced InstanceCount
#define _np4_x12CommandListDrawInstanced StartVertexLocation
#define _np5_x12CommandListDrawInstanced StartInstanceLocation

#define _np1_x12CommandListDrawIndexedInstanced pCommandList
#define _np2_x12CommandListDrawIndexedInstanced IndexCountPerInstance
#define _np3_x12CommandListDrawIndexedInstanced InstanceCount
#define _np4_x12CommandListDrawIndexedInstanced StartIndexLocation
#define _np5_x12CommandListDrawIndexedInstanced BaseVertexLocation
#define _np6_x12CommandListDrawIndexedInstanced StartInstanceLocation

#define _np1_x12CommandListDispatch pCommandList
#define _np2_x12CommandListDispatch ThreadGroupCountX
#define _np3_x12CommandListDispatch ThreadGroupCountY
#define _np4_x12CommandListDispatch ThreadGroupCountZ

#define _np1_x12CommandListSetDescriptorHeaps pCommandList
#define _np2_x12CommandListSetDescriptorHeaps NumDescriptorHeaps
#define _np3_x12CommandListSetDescriptorHeaps ppDescriptorHeaps

#define _np1_x12CommandListSetGraphicsRootSignature pCommandList
#define _np2_x12CommandListSetGraphicsRootSignature pRootSignature

#define _np1_x12CommandListSetGraphicsRoot32BitConstant pCommandList
#define _np2_x12CommandListSetGraphicsRoot32BitConstant RootParameterIndex
#define _np3_x12CommandListSetGraphicsRoot32BitConstant SrcData
#define _np4_x12CommandListSetGraphicsRoot32BitConstant DestOffsetIn32BitValues

#define _np1_x12CommandListSetGraphicsRoot32BitConstants pCommandList
#define _np2_x12CommandListSetGraphicsRoot32BitConstants RootParameterIndex
#define _np3_x12CommandListSetGraphicsRoot32BitConstants Num32BitValuesToSet
#define _np4_x12CommandListSetGraphicsRoot32BitConstants pSrcData
#define _np5_x12CommandListSetGraphicsRoot32BitConstants DestOffsetIn32BitValues

#define _np1_x12CommandListSetGraphicsRootDescriptorTable pCommandList
#define _np2_x12CommandListSetGraphicsRootDescriptorTable RootParameterIndex
#define _np3_x12CommandListSetGraphicsRootDescriptorTable BaseDescriptor

#define _np1_x12CommandListSetGraphicsRootUnorderedAccessView pCommandList
#define _np2_x12CommandListSetGraphicsRootUnorderedAccessView RootParameterIndex
#define _np3_x12CommandListSetGraphicsRootUnorderedAccessView BufferLocation

#define _np1_x12CommandListSetGraphicsRootShaderResourceView pCommandList
#define _np2_x12CommandListSetGraphicsRootShaderResourceView RootParameterIndex
#define _np3_x12CommandListSetGraphicsRootShaderResourceView BufferLocation

#define _np1_x12CommandListSetGraphicsRootConstantBufferView pCommandList
#define _np2_x12CommandListSetGraphicsRootConstantBufferView RootParameterIndex
#define _np3_x12CommandListSetGraphicsRootConstantBufferView BufferLocation

#define _np1_x12CommandListSetComputeRootSignature pCommandList
#define _np2_x12CommandListSetComputeRootSignature pRootSignature

#define _np1_x12CommandListSetComputeRoot32BitConstant pCommandList
#define _np2_x12CommandListSetComputeRoot32BitConstant RootParameterIndex
#define _np3_x12CommandListSetComputeRoot32BitConstant SrcData
#define _np4_x12CommandListSetComputeRoot32BitConstant DestOffsetIn32BitValues

#define _np1_x12CommandListSetComputeRoot32BitConstants pCommandList
#define _np2_x12CommandListSetComputeRoot32BitConstants RootParameterIndex
#define _np3_x12CommandListSetComputeRoot32BitConstants Num32BitValuesToSet
#define _np4_x12CommandListSetComputeRoot32BitConstants pSrcData
#define _np5_x12CommandListSetComputeRoot32BitConstants DestOffsetIn32BitValues

#define _np1_x12CommandListSetComputeRootDescriptorTable pCommandList
#define _np2_x12CommandListSetComputeRootDescriptorTable RootParameterIndex
#define _np3_x12CommandListSetComputeRootDescriptorTable BaseDescriptor

#define _np1_x12CommandListSetComputeRootUnorderedAccessView pCommandList
#define _np2_x12CommandListSetComputeRootUnorderedAccessView RootParameterIndex
#define _np3_x12CommandListSetComputeRootUnorderedAccessView BufferLocation

#define _np1_x12CommandListSetComputeRootShaderResourceView pCommandList
#define _np2_x12CommandListSetComputeRootShaderResourceView RootParameterIndex
#define _np3_x12CommandListSetComputeRootShaderResourceView BufferLocation

#define _np1_x12CommandListSetComputeRootConstantBufferView pCommandList
#define _np2_x12CommandListSetComputeRootConstantBufferView RootParameterIndex
#define _np3_x12CommandListSetComputeRootConstantBufferView BufferLocation

#define _np1_x12CommandListClearState pCommandList
#define _np2_x12CommandListClearState pPipelineState

#define _np1_x12CommandListSetPipelineState pCommandList
#define _np2_x12CommandListSetPipelineState pPipelineState

#define _np1_x12CommandListIASetPrimitiveTopology pCommandList
#define _np2_x12CommandListIASetPrimitiveTopology PrimitiveTopology

#define _np1_x12CommandListIASetIndexBuffer pCommandList
#define _np2_x12CommandListIASetIndexBuffer pView

#define _np1_x12CommandListOMSetStencilRef pCommandList
#define _np2_x12CommandListOMSetStencilRef StencilRef

#define _np1_x12CommandListOMSetBlendFactor pCommandList
#define _np2_x12CommandListOMSetBlendFactor BlendFactor4Values

#define _np1_x12CommandListRSSetViewports pCommandList
#define _np2_x12CommandListRSSetViewports NumViewports
#define _np3_x12CommandListRSSetViewports pViewports

#define _np1_x12CommandListRSSetScissorRects pCommandList
#define _np2_x12CommandListRSSetScissorRects NumRects
#define _np3_x12CommandListRSSetScissorRects pRects

#define _np1_x12CommandListClearRenderTargetView pCommandList
#define _np2_x12CommandListClearRenderTargetView RenderTargetView
#define _np3_x12CommandListClearRenderTargetView ColorRGBA[4]
#define _np4_x12CommandListClearRenderTargetView NumRects
#define _np5_x12CommandListClearRenderTargetView pRects

#define _np1_x12CommandListClearDepthStencilView pCommandList
#define _np2_x12CommandListClearDepthStencilView DepthStencilView
#define _np3_x12CommandListClearDepthStencilView ClearFlags
#define _np4_x12CommandListClearDepthStencilView Depth
#define _np5_x12CommandListClearDepthStencilView char
#define _np6_x12CommandListClearDepthStencilView unsigned
#define _np7_x12CommandListClearDepthStencilView D3D12_RECT*
#define _np8_x12CommandListClearDepthStencilView 

#define _np1_x12CommandListDiscardResource pCommandList
#define _np2_x12CommandListDiscardResource pResource
#define _np3_x12CommandListDiscardResource pRegion

#define _np1_x12CommandListOMSetRenderTargets pCommandList
#define _np2_x12CommandListOMSetRenderTargets NumRenderTargetDescriptors
#define _np3_x12CommandListOMSetRenderTargets pRenderTargetDescriptors
#define _np4_x12CommandListOMSetRenderTargets RTsSingleHandleToDescriptorRange
#define _np5_x12CommandListOMSetRenderTargets pDepthStencilDescriptor

#define _np1_x12CommandListResolveSubresource pCommandList
#define _np2_x12CommandListResolveSubresource pDstResource
#define _np3_x12CommandListResolveSubresource DstSubresource
#define _np4_x12CommandListResolveSubresource pSrcResource
#define _np5_x12CommandListResolveSubresource SrcSubresource
#define _np6_x12CommandListResolveSubresource Format

#define _np1_x12CommandListResourceBarrier pCommandList
#define _np2_x12CommandListResourceBarrier NumBarriers
#define _np3_x12CommandListResourceBarrier pBarriers

#define _np1_x12CommandQueueWait pCommandQueue
#define _np2_x12CommandQueueWait pFence
#define _np3_x12CommandQueueWait Value
#define _np4_x12CommandQueueWait optionalFile
#define _np5_x12CommandQueueWait optionalLine

#define _np1_x12CommandQueueExecuteCommandLists pCommandQueue
#define _np2_x12CommandQueueExecuteCommandLists NumCommandLists
#define _np3_x12CommandQueueExecuteCommandLists ppCommandLists
#define _np4_x12CommandQueueExecuteCommandLists optionalFile
#define _np5_x12CommandQueueExecuteCommandLists optionalLine

#define _np1_x12CommandQueueSignal pCommandQueue
#define _np2_x12CommandQueueSignal pFence
#define _np3_x12CommandQueueSignal Value
#define _np4_x12CommandQueueSignal optionalFile
#define _np5_x12CommandQueueSignal optionalLine

#define _np1_x12FactoryIsCurrent pFactory
#define _np2_x12FactoryIsCurrent optionalFile
#define _np3_x12FactoryIsCurrent optionalLine

#define _np1_x12AdapterGetDesc2 pAdapter
#define _np2_x12AdapterGetDesc2 outDesc
#define _np3_x12AdapterGetDesc2 optionalFile
#define _np4_x12AdapterGetDesc2 optionalLine

#define _np1_x12AdapterEnumOutputs pAdapter
#define _np2_x12AdapterEnumOutputs Output
#define _np3_x12AdapterEnumOutputs outpOutput
#define _np4_x12AdapterEnumOutputs optionalFile
#define _np5_x12AdapterEnumOutputs optionalLine

#define _np1_x12DeviceGetAdapterLuid pDevice
#define _np2_x12DeviceGetAdapterLuid outLuid
#define _np3_x12DeviceGetAdapterLuid optionalFile
#define _np4_x12DeviceGetAdapterLuid optionalLine

#define _np1_x12DeviceGetDescriptorHandleIncrementSize pDevice
#define _np2_x12DeviceGetDescriptorHandleIncrementSize DescriptorHeapType
#define _np3_x12DeviceGetDescriptorHandleIncrementSize optionalFile
#define _np4_x12DeviceGetDescriptorHandleIncrementSize optionalLine

#define _np1_x12DeviceCheckFeatureSupport pDevice
#define _np2_x12DeviceCheckFeatureSupport Feature
#define _np3_x12DeviceCheckFeatureSupport pFeatureSupportData
#define _np4_x12DeviceCheckFeatureSupport FeatureSupportDataSize
#define _np5_x12DeviceCheckFeatureSupport optionalFile
#define _np6_x12DeviceCheckFeatureSupport optionalLine

#define _np1_x12DeviceGetDeviceRemovedReason pDevice
#define _np2_x12DeviceGetDeviceRemovedReason optionalFile
#define _np3_x12DeviceGetDeviceRemovedReason optionalLine

#define _np1_x12DeviceSetStablePowerState pDevice
#define _np2_x12DeviceSetStablePowerState Enable
#define _np3_x12DeviceSetStablePowerState optionalFile
#define _np4_x12DeviceSetStablePowerState optionalLine

#define _np1_x12FactoryCreateSwapChainForHwnd pFactory
#define _np2_x12FactoryCreateSwapChainForHwnd pCommandQueue
#define _np3_x12FactoryCreateSwapChainForHwnd hWnd
#define _np4_x12FactoryCreateSwapChainForHwnd pDesc
#define _np5_x12FactoryCreateSwapChainForHwnd pFullscreenDesc
#define _np6_x12FactoryCreateSwapChainForHwnd pRestrictToOutput
#define _np7_x12FactoryCreateSwapChainForHwnd outpSwapChain
#define _np8_x12FactoryCreateSwapChainForHwnd optionalFile
#define _np9_x12FactoryCreateSwapChainForHwnd optionalLine

#define _np1_x12FactoryCreateSwapChainForCoreWindow pFactory
#define _np2_x12FactoryCreateSwapChainForCoreWindow pCommandQueue
#define _np3_x12FactoryCreateSwapChainForCoreWindow pWindow
#define _np4_x12FactoryCreateSwapChainForCoreWindow pDesc
#define _np5_x12FactoryCreateSwapChainForCoreWindow pRestrictToOutput
#define _np6_x12FactoryCreateSwapChainForCoreWindow outpSwapChain
#define _np7_x12FactoryCreateSwapChainForCoreWindow optionalFile
#define _np8_x12FactoryCreateSwapChainForCoreWindow optionalLine

#define _np1_x12FactoryCreateSwapChainForComposition pFactory
#define _np2_x12FactoryCreateSwapChainForComposition pCommandQueue
#define _np3_x12FactoryCreateSwapChainForComposition pDesc
#define _np4_x12FactoryCreateSwapChainForComposition pRestrictToOutput
#define _np5_x12FactoryCreateSwapChainForComposition outpSwapChain
#define _np6_x12FactoryCreateSwapChainForComposition optionalFile
#define _np7_x12FactoryCreateSwapChainForComposition optionalLine

#define _np1_x12FactoryMakeWindowAssociation pFactory
#define _np2_x12FactoryMakeWindowAssociation WindowHandle
#define _np3_x12FactoryMakeWindowAssociation Flags
#define _np4_x12FactoryMakeWindowAssociation optionalFile
#define _np5_x12FactoryMakeWindowAssociation optionalLine

#define _np1_x12FactoryGetWindowAssociation pFactory
#define _np2_x12FactoryGetWindowAssociation outWindowHandle
#define _np3_x12FactoryGetWindowAssociation optionalFile
#define _np4_x12FactoryGetWindowAssociation optionalLine

#define _np1_x12FactoryRegisterOcclusionStatusWindow pFactory
#define _np2_x12FactoryRegisterOcclusionStatusWindow WindowHandle
#define _np3_x12FactoryRegisterOcclusionStatusWindow wMsg
#define _np4_x12FactoryRegisterOcclusionStatusWindow pdwCookie
#define _np5_x12FactoryRegisterOcclusionStatusWindow optionalFile
#define _np6_x12FactoryRegisterOcclusionStatusWindow optionalLine

#define _np1_x12FactoryRegisterOcclusionStatusEvent pFactory
#define _np2_x12FactoryRegisterOcclusionStatusEvent hEvent
#define _np3_x12FactoryRegisterOcclusionStatusEvent pdwCookie
#define _np4_x12FactoryRegisterOcclusionStatusEvent optionalFile
#define _np5_x12FactoryRegisterOcclusionStatusEvent optionalLine

#define _np1_x12FactoryUnregisterOcclusionStatus pFactory
#define _np2_x12FactoryUnregisterOcclusionStatus dwCookie
#define _np3_x12FactoryUnregisterOcclusionStatus optionalFile
#define _np4_x12FactoryUnregisterOcclusionStatus optionalLine

#define _np1_x12SwapChainGetBuffer pSwapChain
#define _np2_x12SwapChainGetBuffer Buffer
#define _np3_x12SwapChainGetBuffer outpSurface
#define _np4_x12SwapChainGetBuffer optionalFile
#define _np5_x12SwapChainGetBuffer optionalLine

#define _np1_x12SwapChainGetCurrentBackBufferIndex pSwapChain
#define _np2_x12SwapChainGetCurrentBackBufferIndex optionalFile
#define _np3_x12SwapChainGetCurrentBackBufferIndex optionalLine

#define _np1_x12SwapChainPresent1 pSwapChain
#define _np2_x12SwapChainPresent1 SyncInterval
#define _np3_x12SwapChainPresent1 PresentFlags
#define _np4_x12SwapChainPresent1 pPresentParameters
#define _np5_x12SwapChainPresent1 optionalFile
#define _np6_x12SwapChainPresent1 optionalLine

#define _np1_x12SwapChainResizeTarget pSwapChain
#define _np2_x12SwapChainResizeTarget pNewTargetParameters
#define _np3_x12SwapChainResizeTarget optionalFile
#define _np4_x12SwapChainResizeTarget optionalLine

#define _np1_x12SwapChainResizeBuffers1 pSwapChain
#define _np2_x12SwapChainResizeBuffers1 BufferCount
#define _np3_x12SwapChainResizeBuffers1 Width
#define _np4_x12SwapChainResizeBuffers1 Height
#define _np5_x12SwapChainResizeBuffers1 Format
#define _np6_x12SwapChainResizeBuffers1 SwapChainFlags
#define _np7_x12SwapChainResizeBuffers1 pCreationNodeMask
#define _np8_x12SwapChainResizeBuffers1 ppPresentQueue
#define _np9_x12SwapChainResizeBuffers1 optionalFile
#define _np10_x12SwapChainResizeBuffers1 optionalLine

#define _np1_x12SwapChainSetFullscreenState pSwapChain
#define _np2_x12SwapChainSetFullscreenState Fullscreen
#define _np3_x12SwapChainSetFullscreenState pTarget
#define _np4_x12SwapChainSetFullscreenState optionalFile
#define _np5_x12SwapChainSetFullscreenState optionalLine

#define _np1_x12SwapChainGetFullscreenDesc pSwapChain
#define _np2_x12SwapChainGetFullscreenDesc outDesc
#define _np3_x12SwapChainGetFullscreenDesc optionalFile
#define _np4_x12SwapChainGetFullscreenDesc optionalLine

#define _np1_x12SwapChainGetLastPresentCount pSwapChain
#define _np2_x12SwapChainGetLastPresentCount outLastPresentCount
#define _np3_x12SwapChainGetLastPresentCount optionalFile
#define _np4_x12SwapChainGetLastPresentCount optionalLine

#define _np1_x12SwapChainGetFrameStatistics pSwapChain
#define _np2_x12SwapChainGetFrameStatistics outStats
#define _np3_x12SwapChainGetFrameStatistics optionalFile
#define _np4_x12SwapChainGetFrameStatistics optionalLine

#define _np1_x12SwapChainSetBackgroundColor pSwapChain
#define _np2_x12SwapChainSetBackgroundColor pColor
#define _np3_x12SwapChainSetBackgroundColor optionalFile
#define _np4_x12SwapChainSetBackgroundColor optionalLine

#define _np1_x12SwapChainGetBackgroundColor pSwapChain
#define _np2_x12SwapChainGetBackgroundColor outColor
#define _np3_x12SwapChainGetBackgroundColor optionalFile
#define _np4_x12SwapChainGetBackgroundColor optionalLine

#define _np1_x12SwapChainSetRotation pSwapChain
#define _np2_x12SwapChainSetRotation Rotation
#define _np3_x12SwapChainSetRotation optionalFile
#define _np4_x12SwapChainSetRotation optionalLine

#define _np1_x12SwapChainGetRotation pSwapChain
#define _np2_x12SwapChainGetRotation outRotation
#define _np3_x12SwapChainGetRotation optionalFile
#define _np4_x12SwapChainGetRotation optionalLine

#define _np1_x12SwapChainSetSourceSize pSwapChain
#define _np2_x12SwapChainSetSourceSize Width
#define _np3_x12SwapChainSetSourceSize Height
#define _np4_x12SwapChainSetSourceSize optionalFile
#define _np5_x12SwapChainSetSourceSize optionalLine

#define _np1_x12SwapChainGetSourceSize pSwapChain
#define _np2_x12SwapChainGetSourceSize outWidth
#define _np3_x12SwapChainGetSourceSize outHeight
#define _np4_x12SwapChainGetSourceSize optionalFile
#define _np5_x12SwapChainGetSourceSize optionalLine

#define _np1_x12SwapChainSetMaximumFrameLatency pSwapChain
#define _np2_x12SwapChainSetMaximumFrameLatency MaxLatency
#define _np3_x12SwapChainSetMaximumFrameLatency optionalFile
#define _np4_x12SwapChainSetMaximumFrameLatency optionalLine

#define _np1_x12SwapChainGetMaximumFrameLatency pSwapChain
#define _np2_x12SwapChainGetMaximumFrameLatency outMaxLatency
#define _np3_x12SwapChainGetMaximumFrameLatency optionalFile
#define _np4_x12SwapChainGetMaximumFrameLatency optionalLine

#define _np1_x12SwapChainGetFrameLatencyWaitableObject pSwapChain
#define _np2_x12SwapChainGetFrameLatencyWaitableObject optionalFile
#define _np3_x12SwapChainGetFrameLatencyWaitableObject optionalLine

#define _np1_x12SwapChainSetMatrixTransform pSwapChain
#define _np2_x12SwapChainSetMatrixTransform pMatrix
#define _np3_x12SwapChainSetMatrixTransform optionalFile
#define _np4_x12SwapChainSetMatrixTransform optionalLine

#define _np1_x12SwapChainGetMatrixTransform pSwapChain
#define _np2_x12SwapChainGetMatrixTransform outMatrix
#define _np3_x12SwapChainGetMatrixTransform optionalFile
#define _np4_x12SwapChainGetMatrixTransform optionalLine

#define _np1_x12SwapChainCheckColorSpaceSupport pSwapChain
#define _np2_x12SwapChainCheckColorSpaceSupport ColorSpace
#define _np3_x12SwapChainCheckColorSpaceSupport outColorSpaceSupport
#define _np4_x12SwapChainCheckColorSpaceSupport optionalFile
#define _np5_x12SwapChainCheckColorSpaceSupport optionalLine

#define _np1_x12SwapChainSetColorSpace1 pSwapChain
#define _np2_x12SwapChainSetColorSpace1 ColorSpace
#define _np3_x12SwapChainSetColorSpace1 optionalFile
#define _np4_x12SwapChainSetColorSpace1 optionalLine

#define _np1_x12OutputGetDesc pOutput
#define _np2_x12OutputGetDesc outDesc
#define _np3_x12OutputGetDesc optionalFile
#define _np4_x12OutputGetDesc optionalLine

#define _np1_x12OutputGetDisplayModeList1 pOutput
#define _np2_x12OutputGetDisplayModeList1 EnumFormat
#define _np3_x12OutputGetDisplayModeList1 Flags
#define _np4_x12OutputGetDisplayModeList1 pNumModes
#define _np5_x12OutputGetDisplayModeList1 outDesc
#define _np6_x12OutputGetDisplayModeList1 optionalFile
#define _np7_x12OutputGetDisplayModeList1 optionalLine

#define _np1_x12OutputFindClosestMatchingMode1 pOutput
#define _np2_x12OutputFindClosestMatchingMode1 pModeToMatch
#define _np3_x12OutputFindClosestMatchingMode1 pClosestMatch
#define _np4_x12OutputFindClosestMatchingMode1 pConcernedDevice
#define _np5_x12OutputFindClosestMatchingMode1 optionalFile
#define _np6_x12OutputFindClosestMatchingMode1 optionalLine

#define _np1_x12OutputWaitForVBlank pOutput
#define _np2_x12OutputWaitForVBlank optionalFile
#define _np3_x12OutputWaitForVBlank optionalLine

#define _np1_x12OutputGetGammaControlCapabilities pOutput
#define _np2_x12OutputGetGammaControlCapabilities outGammaCaps
#define _np3_x12OutputGetGammaControlCapabilities optionalFile
#define _np4_x12OutputGetGammaControlCapabilities optionalLine

#define _np1_x12OutputSetGammaControl pOutput
#define _np2_x12OutputSetGammaControl pArray
#define _np3_x12OutputSetGammaControl optionalFile
#define _np4_x12OutputSetGammaControl optionalLine

#define _np1_x12OutputGetGammaControl pOutput
#define _np2_x12OutputGetGammaControl outArray
#define _np3_x12OutputGetGammaControl optionalFile
#define _np4_x12OutputGetGammaControl optionalLine

#define _np1_x12OutputGetFrameStatistics pOutput
#define _np2_x12OutputGetFrameStatistics outStats
#define _np3_x12OutputGetFrameStatistics optionalFile
#define _np4_x12OutputGetFrameStatistics optionalLine

#define _np1_x12OutputSupportsOverlays pOutput
#define _np2_x12OutputSupportsOverlays optionalFile
#define _np3_x12OutputSupportsOverlays optionalLine

#define _np1_x12OutputCheckOverlaySupport pOutput
#define _np2_x12OutputCheckOverlaySupport EnumFormat
#define _np3_x12OutputCheckOverlaySupport pConcernedDevice
#define _np4_x12OutputCheckOverlaySupport pFlags
#define _np5_x12OutputCheckOverlaySupport optionalFile
#define _np6_x12OutputCheckOverlaySupport optionalLine

#define _np1_x12OutputCheckOverlayColorSpaceSupport pOutput
#define _np2_x12OutputCheckOverlayColorSpaceSupport Format
#define _np3_x12OutputCheckOverlayColorSpaceSupport ColorSpace
#define _np4_x12OutputCheckOverlayColorSpaceSupport pConcernedDevice
#define _np5_x12OutputCheckOverlayColorSpaceSupport outFlags
#define _np6_x12OutputCheckOverlayColorSpaceSupport optionalFile
#define _np7_x12OutputCheckOverlayColorSpaceSupport optionalLine

#define _np1_x12ObjectSetName handle
#define _np2_x12ObjectSetName Name
#define _np3_x12ObjectSetName optionalFile
#define _np4_x12ObjectSetName optionalLine

#define _np1_x12Release handle
#define _np2_x12Release optionalFile
#define _np3_x12Release optionalLine

#define _np1_x12CommandListSetMarker handle
#define _np2_x12CommandListSetMarker Metadata
#define _np3_x12CommandListSetMarker pData
#define _np4_x12CommandListSetMarker Size

#define _np1_x12CommandListBeginEvent handle
#define _np2_x12CommandListBeginEvent Metadata
#define _np3_x12CommandListBeginEvent pData
#define _np4_x12CommandListBeginEvent Size

#define _np1_x12CommandListEndEvent handle

#define _np1_x12CommandQueueSetMarker handle
#define _np2_x12CommandQueueSetMarker Metadata
#define _np3_x12CommandQueueSetMarker pData
#define _np4_x12CommandQueueSetMarker Size

#define _np1_x12CommandQueueBeginEvent handle
#define _np2_x12CommandQueueBeginEvent Metadata
#define _np3_x12CommandQueueBeginEvent pData
#define _np4_x12CommandQueueBeginEvent Size

#define _np1_x12CommandQueueEndEvent handle

