#pragma once

#define _np1_red2CreateStructDeclaration context
#define _np2_red2CreateStructDeclaration gpu
#define _np3_red2CreateStructDeclaration handleName
#define _np4_red2CreateStructDeclaration structDeclarationMembersCount
#define _np5_red2CreateStructDeclaration structDeclarationMembers
#define _np6_red2CreateStructDeclaration structDeclarationMembersArrayROCount
#define _np7_red2CreateStructDeclaration structDeclarationMembersArrayRO
#define _np8_red2CreateStructDeclaration procedureParametersHandlesDeclaration
#define _np9_red2CreateStructDeclaration outStructDeclaration
#define _np10_red2CreateStructDeclaration outStatuses
#define _np11_red2CreateStructDeclaration optionalFile
#define _np12_red2CreateStructDeclaration optionalLine
#define _np13_red2CreateStructDeclaration optionalUserData

#define _np1_red2CreateProcedureParameters context
#define _np2_red2CreateProcedureParameters gpu
#define _np3_red2CreateProcedureParameters handleName
#define _np4_red2CreateProcedureParameters procedureParametersDeclaration
#define _np5_red2CreateProcedureParameters outProcedureParameters
#define _np6_red2CreateProcedureParameters outStatuses
#define _np7_red2CreateProcedureParameters optionalFile
#define _np8_red2CreateProcedureParameters optionalLine
#define _np9_red2CreateProcedureParameters optionalUserData

#define _np1_red2CreateCalls context
#define _np2_red2CreateCalls gpu
#define _np3_red2CreateCalls handleName
#define _np4_red2CreateCalls queueFamilyIndex
#define _np5_red2CreateCalls outCalls
#define _np6_red2CreateCalls outStatuses
#define _np7_red2CreateCalls optionalFile
#define _np8_red2CreateCalls optionalLine
#define _np9_red2CreateCalls optionalUserData

#define _np1_red2CreateCallsReusable context
#define _np2_red2CreateCallsReusable gpu
#define _np3_red2CreateCallsReusable handleName
#define _np4_red2CreateCallsReusable queueFamilyIndex
#define _np5_red2CreateCallsReusable outCalls
#define _np6_red2CreateCallsReusable outStatuses
#define _np7_red2CreateCallsReusable optionalFile
#define _np8_red2CreateCallsReusable optionalLine
#define _np9_red2CreateCallsReusable optionalUserData

#define _np1_red2CreateWsiTransientGpuSignal context
#define _np2_red2CreateWsiTransientGpuSignal gpu
#define _np3_red2CreateWsiTransientGpuSignal present
#define _np4_red2CreateWsiTransientGpuSignal presentImageIndex
#define _np5_red2CreateWsiTransientGpuSignal outGpuSignal
#define _np6_red2CreateWsiTransientGpuSignal outStatuses
#define _np7_red2CreateWsiTransientGpuSignal optionalFile
#define _np8_red2CreateWsiTransientGpuSignal optionalLine
#define _np9_red2CreateWsiTransientGpuSignal optionalUserData

#define _np1_red2DestroyContext context
#define _np2_red2DestroyContext optionalFile
#define _np3_red2DestroyContext optionalLine
#define _np4_red2DestroyContext optionalUserData

#define _np1_red2DestroyStructDeclaration context
#define _np2_red2DestroyStructDeclaration gpu
#define _np3_red2DestroyStructDeclaration structDeclaration
#define _np4_red2DestroyStructDeclaration optionalFile
#define _np5_red2DestroyStructDeclaration optionalLine
#define _np6_red2DestroyStructDeclaration optionalUserData

#define _np1_red2DestroyProcedureParameters context
#define _np2_red2DestroyProcedureParameters gpu
#define _np3_red2DestroyProcedureParameters procedureParameters
#define _np4_red2DestroyProcedureParameters optionalFile
#define _np5_red2DestroyProcedureParameters optionalLine
#define _np6_red2DestroyProcedureParameters optionalUserData

#define _np1_red2DestroyCalls context
#define _np2_red2DestroyCalls gpu
#define _np3_red2DestroyCalls calls
#define _np4_red2DestroyCalls optionalFile
#define _np5_red2DestroyCalls optionalLine
#define _np6_red2DestroyCalls optionalUserData

#define _np1_red2StructDeclarationGetRedHandle structDeclaration

#define _np1_red2StructDeclarationGetMembersPointer structDeclaration

#define _np1_red2StructDeclarationGetMembersCounts structDeclaration
#define _np2_red2StructDeclarationGetMembersCounts outStructDeclarationMembersCount
#define _np3_red2StructDeclarationGetMembersCounts outMembersOfTypeArrayROConstantCount
#define _np4_red2StructDeclarationGetMembersCounts outMembersOfTypeArrayROOrArrayRWCount
#define _np5_red2StructDeclarationGetMembersCounts outMembersOfTypeTextureROCount
#define _np6_red2StructDeclarationGetMembersCounts outMembersOfTypeTextureRWCount
#define _np7_red2StructDeclarationGetMembersCounts outMembersOfTypeInlineSamplerCount
#define _np8_red2StructDeclarationGetMembersCounts outMembersOfTypeSamplerCount

#define _np1_red2ProcedureParametersGetRedHandle procedureParameters

#define _np1_red2ProcedureParametersGetStructDeclaration procedureParameters
#define _np2_red2ProcedureParametersGetStructDeclaration structIndex

#define _np1_red2CallsGetRedHandles calls
#define _np2_red2CallsGetRedHandles outContext
#define _np3_red2CallsGetRedHandles outGpu
#define _np4_red2CallsGetRedHandles outCalls

#define _np1_red2CallsSet context
#define _np2_red2CallsSet gpu
#define _np3_red2CallsSet calls
#define _np4_red2CallsSet callsMemory
#define _np5_red2CallsSet callsReusable
#define _np6_red2CallsSet outStatuses
#define _np7_red2CallsSet optionalFile
#define _np8_red2CallsSet optionalLine
#define _np9_red2CallsSet optionalUserData

#define _np1_red2CallsEnd context
#define _np2_red2CallsEnd gpu
#define _np3_red2CallsEnd calls
#define _np4_red2CallsEnd callsMemory
#define _np5_red2CallsEnd outStatuses
#define _np6_red2CallsEnd optionalFile
#define _np7_red2CallsEnd optionalLine
#define _np8_red2CallsEnd optionalUserData

#define _np1_red2CallsFreeAllInlineStructsMemorys context
#define _np2_red2CallsFreeAllInlineStructsMemorys gpu
#define _np3_red2CallsFreeAllInlineStructsMemorys calls
#define _np4_red2CallsFreeAllInlineStructsMemorys optionalFile
#define _np5_red2CallsFreeAllInlineStructsMemorys optionalLine
#define _np6_red2CallsFreeAllInlineStructsMemorys optionalUserData

#define _np1_red2CallAllocateAndSetInlineStructsMemory calls
#define _np2_red2CallAllocateAndSetInlineStructsMemory structsMemoryHandleName
#define _np3_red2CallAllocateAndSetInlineStructsMemory maxStructsCount
#define _np4_red2CallAllocateAndSetInlineStructsMemory maxStructsOfTypeSamplerCount
#define _np5_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeArrayROConstantCount
#define _np6_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeArrayROOrArrayRWCount
#define _np7_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeTextureROCount
#define _np8_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeTextureRWCount
#define _np9_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeInlineSamplerCount
#define _np10_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeSamplerCount
#define _np11_red2CallAllocateAndSetInlineStructsMemory outStatuses
#define _np12_red2CallAllocateAndSetInlineStructsMemory optionalFile
#define _np13_red2CallAllocateAndSetInlineStructsMemory optionalLine
#define _np14_red2CallAllocateAndSetInlineStructsMemory optionalUserData

#define _np1_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters calls
#define _np2_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters structsMemoryHandleName
#define _np3_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters procedureParametersCount
#define _np4_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters procedureParameters
#define _np5_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters outStatuses
#define _np6_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters optionalFile
#define _np7_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters optionalLine
#define _np8_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters optionalUserData

#define _np1_red2CallSuballocateAndSetProcedureParametersInlineStruct calls
#define _np2_red2CallSuballocateAndSetProcedureParametersInlineStruct procedureType
#define _np3_red2CallSuballocateAndSetProcedureParametersInlineStruct procedureParameters
#define _np4_red2CallSuballocateAndSetProcedureParametersInlineStruct structIndex
#define _np5_red2CallSuballocateAndSetProcedureParametersInlineStruct structAllRedHandlesInParameterArrayOrderOfRed2CreateStructDeclarationStructDeclarationMembers
#define _np6_red2CallSuballocateAndSetProcedureParametersInlineStruct outStatuses
#define _np7_red2CallSuballocateAndSetProcedureParametersInlineStruct optionalFile
#define _np8_red2CallSuballocateAndSetProcedureParametersInlineStruct optionalLine
#define _np9_red2CallSuballocateAndSetProcedureParametersInlineStruct optionalUserData

#define _np1_red2PresentGetImageIndex context
#define _np2_red2PresentGetImageIndex gpu
#define _np3_red2PresentGetImageIndex present
#define _np4_red2PresentGetImageIndex signalCpuSignal
#define _np5_red2PresentGetImageIndex signalGpuSignal
#define _np6_red2PresentGetImageIndex outImageIndex
#define _np7_red2PresentGetImageIndex outStatuses
#define _np8_red2PresentGetImageIndex optionalFile
#define _np9_red2PresentGetImageIndex optionalLine
#define _np10_red2PresentGetImageIndex optionalUserData

#define _np1_red2QueueSubmit context
#define _np2_red2QueueSubmit gpu
#define _np3_red2QueueSubmit queue
#define _np4_red2QueueSubmit timelinesCount
#define _np5_red2QueueSubmit timelines
#define _np6_red2QueueSubmit outQueueSubmissionTicketArrayIndex
#define _np7_red2QueueSubmit outQueueSubmissionTicket
#define _np8_red2QueueSubmit whenQueueSubmissionIsFinishedDestroyHandlesCount
#define _np9_red2QueueSubmit whenQueueSubmissionIsFinishedDestroyHandles
#define _np10_red2QueueSubmit whenQueueSubmissionIsFinishedDestroyHandlesHandleType
#define _np11_red2QueueSubmit optionalCustomHandleTypeDestroyCallback
#define _np12_red2QueueSubmit outStatuses
#define _np13_red2QueueSubmit optionalFile
#define _np14_red2QueueSubmit optionalLine
#define _np15_red2QueueSubmit optionalUserData

#define _np1_red2IsQueueSubmissionFinished queueSubmissionTicketArrayIndex
#define _np2_red2IsQueueSubmissionFinished queueSubmissionTicket
#define _np3_red2IsQueueSubmissionFinished optionalFile
#define _np4_red2IsQueueSubmissionFinished optionalLine
#define _np5_red2IsQueueSubmissionFinished optionalUserData

#define _np1_red2IsQueueSubmissionFinishedByTicketAlone queueSubmissionTicket
#define _np2_red2IsQueueSubmissionFinishedByTicketAlone optionalFile
#define _np3_red2IsQueueSubmissionFinishedByTicketAlone optionalLine
#define _np4_red2IsQueueSubmissionFinishedByTicketAlone optionalUserData

#define _np1_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket context
#define _np2_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket gpu
#define _np3_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket queueSubmissionTicket
#define _np4_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket outStatuses
#define _np5_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket optionalFile
#define _np6_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket optionalLine
#define _np7_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket optionalUserData

#define _np1_red2WaitForQueueSubmissionToFinish queueSubmissionTicketArrayIndex
#define _np2_red2WaitForQueueSubmissionToFinish queueSubmissionTicket
#define _np3_red2WaitForQueueSubmissionToFinish outStatuses
#define _np4_red2WaitForQueueSubmissionToFinish optionalFile
#define _np5_red2WaitForQueueSubmissionToFinish optionalLine
#define _np6_red2WaitForQueueSubmissionToFinish optionalUserData

#define _np1_red2WaitForQueueSubmissionToFinishByTicketAlone queueSubmissionTicket
#define _np2_red2WaitForQueueSubmissionToFinishByTicketAlone outStatuses
#define _np3_red2WaitForQueueSubmissionToFinishByTicketAlone optionalFile
#define _np4_red2WaitForQueueSubmissionToFinishByTicketAlone optionalLine
#define _np5_red2WaitForQueueSubmissionToFinishByTicketAlone optionalUserData

#define _np1_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket context
#define _np2_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket gpu
#define _np3_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket queueSubmissionTicket
#define _np4_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket outStatuses
#define _np5_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket optionalFile
#define _np6_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket optionalLine
#define _np7_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket optionalUserData

#define _np1_red2WaitForAllQueueSubmissionsToFinish context
#define _np2_red2WaitForAllQueueSubmissionsToFinish gpu
#define _np3_red2WaitForAllQueueSubmissionsToFinish outStatuses
#define _np4_red2WaitForAllQueueSubmissionsToFinish optionalFile
#define _np5_red2WaitForAllQueueSubmissionsToFinish optionalLine
#define _np6_red2WaitForAllQueueSubmissionsToFinish optionalUserData

#define _np1_red2CallUsageAliasOrderBarrier address
#define _np2_red2CallUsageAliasOrderBarrier calls
#define _np3_red2CallUsageAliasOrderBarrier context
#define _np4_red2CallUsageAliasOrderBarrier gpu
#define _np5_red2CallUsageAliasOrderBarrier arrayUsagesCount
#define _np6_red2CallUsageAliasOrderBarrier arrayUsages
#define _np7_red2CallUsageAliasOrderBarrier imageUsagesCount
#define _np8_red2CallUsageAliasOrderBarrier imageUsages
#define _np9_red2CallUsageAliasOrderBarrier aliasesCount
#define _np10_red2CallUsageAliasOrderBarrier aliases
#define _np11_red2CallUsageAliasOrderBarrier ordersCount
#define _np12_red2CallUsageAliasOrderBarrier orders
#define _np13_red2CallUsageAliasOrderBarrier dependencyByRegion

