#pragma once

#define _np1_redRteCreateContext mallocFn
#define _np2_redRteCreateContext freeFn
#define _np3_redRteCreateContext optionalMallocTagged
#define _np4_redRteCreateContext optionalFreeTagged
#define _np5_redRteCreateContext debugCallback
#define _np6_redRteCreateContext sdkVersion
#define _np7_redRteCreateContext sdkExtensionsCount
#define _np8_redRteCreateContext sdkExtensions
#define _np9_redRteCreateContext optionalProgramName
#define _np10_redRteCreateContext optionalProgramVersion
#define _np11_redRteCreateContext optionalEngineName
#define _np12_redRteCreateContext optionalEngineVersion
#define _np13_redRteCreateContext optionalSettings
#define _np14_redRteCreateContext outContext
#define _np15_redRteCreateContext outStatuses
#define _np16_redRteCreateContext optionalFile
#define _np17_redRteCreateContext optionalLine
#define _np18_redRteCreateContext optionalUserData
#define _np19_redRteCreateContext rteParameters

#define _np1_redRteDestroyContext context
#define _np2_redRteDestroyContext optionalFile
#define _np3_redRteDestroyContext optionalLine
#define _np4_redRteDestroyContext optionalUserData
#define _np5_redRteDestroyContext rteParameters

#define _np1_redRteCreateQueue rteContext
#define _np2_redRteCreateQueue handleName
#define _np3_redRteCreateQueue queueFlags
#define _np4_redRteCreateQueue queuePriority
#define _np5_redRteCreateQueue outRteQueue
#define _np6_redRteCreateQueue outStatuses
#define _np7_redRteCreateQueue optionalFile
#define _np8_redRteCreateQueue optionalLine
#define _np9_redRteCreateQueue optionalUserData
#define _np10_redRteCreateQueue rteParameters

#define _np1_redRteArrayGetGpuAddress rteContext
#define _np2_redRteArrayGetGpuAddress gpu
#define _np3_redRteArrayGetGpuAddress array
#define _np4_redRteArrayGetGpuAddress optionalFile
#define _np5_redRteArrayGetGpuAddress optionalLine
#define _np6_redRteArrayGetGpuAddress optionalUserData
#define _np7_redRteArrayGetGpuAddress rteParameters

#define _np1_redRteCreateHelperAllocatorDma rteContext
#define _np2_redRteCreateHelperAllocatorDma outHelperAllocatorDma
#define _np3_redRteCreateHelperAllocatorDma outStatuses
#define _np4_redRteCreateHelperAllocatorDma optionalFile
#define _np5_redRteCreateHelperAllocatorDma optionalLine
#define _np6_redRteCreateHelperAllocatorDma optionalUserData
#define _np7_redRteCreateHelperAllocatorDma rteParameters

#define _np1_redRteDestroyHelperAllocatorDma helperAllocatorDma
#define _np2_redRteDestroyHelperAllocatorDma optionalFile
#define _np3_redRteDestroyHelperAllocatorDma optionalLine
#define _np4_redRteDestroyHelperAllocatorDma optionalUserData
#define _np5_redRteDestroyHelperAllocatorDma rteParameters

#define _np1_redRteHelperAllocatorDmaCreateArray helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaCreateArray arrayInfo
#define _np3_redRteHelperAllocatorDmaCreateArray memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np4_redRteHelperAllocatorDmaCreateArray outRteHelperArray
#define _np5_redRteHelperAllocatorDmaCreateArray outStatuses
#define _np6_redRteHelperAllocatorDmaCreateArray optionalFile
#define _np7_redRteHelperAllocatorDmaCreateArray optionalLine
#define _np8_redRteHelperAllocatorDmaCreateArray optionalUserData
#define _np9_redRteHelperAllocatorDmaCreateArray rteParameters

#define _np1_redRteHelperAllocatorDmaCreateImage helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaCreateImage imageInfo
#define _np3_redRteHelperAllocatorDmaCreateImage memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np4_redRteHelperAllocatorDmaCreateImage outRteHelperImage
#define _np5_redRteHelperAllocatorDmaCreateImage outStatuses
#define _np6_redRteHelperAllocatorDmaCreateImage optionalFile
#define _np7_redRteHelperAllocatorDmaCreateImage optionalLine
#define _np8_redRteHelperAllocatorDmaCreateImage optionalUserData
#define _np9_redRteHelperAllocatorDmaCreateImage rteParameters

#define _np1_redRteHelperAllocatorDmaCreateArraySimple helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaCreateArraySimple arrayBytesCount
#define _np3_redRteHelperAllocatorDmaCreateArraySimple arrayUsageFlags
#define _np4_redRteHelperAllocatorDmaCreateArraySimple memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np5_redRteHelperAllocatorDmaCreateArraySimple outRteHelperArray
#define _np6_redRteHelperAllocatorDmaCreateArraySimple outStatuses
#define _np7_redRteHelperAllocatorDmaCreateArraySimple optionalFile
#define _np8_redRteHelperAllocatorDmaCreateArraySimple optionalLine
#define _np9_redRteHelperAllocatorDmaCreateArraySimple optionalUserData
#define _np10_redRteHelperAllocatorDmaCreateArraySimple rteParameters

#define _np1_redRteHelperAllocatorDmaCreateArraySimpleWithData helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaCreateArraySimpleWithData callsSetToUploadArrayData
#define _np3_redRteHelperAllocatorDmaCreateArraySimpleWithData arrayDataBytesCount
#define _np4_redRteHelperAllocatorDmaCreateArraySimpleWithData arrayData
#define _np5_redRteHelperAllocatorDmaCreateArraySimpleWithData arrayUsageFlags
#define _np6_redRteHelperAllocatorDmaCreateArraySimpleWithData memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np7_redRteHelperAllocatorDmaCreateArraySimpleWithData outRteHelperArray
#define _np8_redRteHelperAllocatorDmaCreateArraySimpleWithData outStatuses
#define _np9_redRteHelperAllocatorDmaCreateArraySimpleWithData optionalFile
#define _np10_redRteHelperAllocatorDmaCreateArraySimpleWithData optionalLine
#define _np11_redRteHelperAllocatorDmaCreateArraySimpleWithData optionalUserData
#define _np12_redRteHelperAllocatorDmaCreateArraySimpleWithData rteParameters

#define _np1_redRteHelperAllocatorDmaCreateImageSimpleWithData helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaCreateImageSimpleWithData callsSetToUploadImageData
#define _np3_redRteHelperAllocatorDmaCreateImageSimpleWithData imageDataBytesCount
#define _np4_redRteHelperAllocatorDmaCreateImageSimpleWithData imageData
#define _np5_redRteHelperAllocatorDmaCreateImageSimpleWithData imageInfo
#define _np6_redRteHelperAllocatorDmaCreateImageSimpleWithData imageLayoutSuggestedDefaultValueIsImageLayoutGeneral
#define _np7_redRteHelperAllocatorDmaCreateImageSimpleWithData outRteHelperImage
#define _np8_redRteHelperAllocatorDmaCreateImageSimpleWithData outStatuses
#define _np9_redRteHelperAllocatorDmaCreateImageSimpleWithData optionalFile
#define _np10_redRteHelperAllocatorDmaCreateImageSimpleWithData optionalLine
#define _np11_redRteHelperAllocatorDmaCreateImageSimpleWithData optionalUserData
#define _np12_redRteHelperAllocatorDmaCreateImageSimpleWithData rteParameters

#define _np1_redRteHelperAllocatorDmaDestroyArray helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaDestroyArray rteHelperArray
#define _np3_redRteHelperAllocatorDmaDestroyArray rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorDmaDestroyArray outStatuses
#define _np5_redRteHelperAllocatorDmaDestroyArray optionalFile
#define _np6_redRteHelperAllocatorDmaDestroyArray optionalLine
#define _np7_redRteHelperAllocatorDmaDestroyArray optionalUserData
#define _np8_redRteHelperAllocatorDmaDestroyArray rteParameters

#define _np1_redRteHelperAllocatorDmaDestroyImage helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaDestroyImage rteHelperImage
#define _np3_redRteHelperAllocatorDmaDestroyImage rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorDmaDestroyImage outStatuses
#define _np5_redRteHelperAllocatorDmaDestroyImage optionalFile
#define _np6_redRteHelperAllocatorDmaDestroyImage optionalLine
#define _np7_redRteHelperAllocatorDmaDestroyImage optionalUserData
#define _np8_redRteHelperAllocatorDmaDestroyImage rteParameters

#define _np1_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory optionalCpuSignal
#define _np3_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory outStatuses
#define _np4_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory optionalFile
#define _np5_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory optionalLine
#define _np6_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory optionalUserData
#define _np7_redRteHelperAllocatorDmaFinalizeAndReleaseStagingMemory rteParameters

#define _np1_redRteHelperAllocatorDmaFinalizeStagingMemory helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaFinalizeStagingMemory optionalCpuSignal
#define _np3_redRteHelperAllocatorDmaFinalizeStagingMemory outStatuses
#define _np4_redRteHelperAllocatorDmaFinalizeStagingMemory optionalFile
#define _np5_redRteHelperAllocatorDmaFinalizeStagingMemory optionalLine
#define _np6_redRteHelperAllocatorDmaFinalizeStagingMemory optionalUserData
#define _np7_redRteHelperAllocatorDmaFinalizeStagingMemory rteParameters

#define _np1_redRteHelperAllocatorDmaReleaseStagingMemory helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaReleaseStagingMemory outStatuses
#define _np3_redRteHelperAllocatorDmaReleaseStagingMemory optionalFile
#define _np4_redRteHelperAllocatorDmaReleaseStagingMemory optionalLine
#define _np5_redRteHelperAllocatorDmaReleaseStagingMemory optionalUserData
#define _np6_redRteHelperAllocatorDmaReleaseStagingMemory rteParameters

#define _np1_redRteHelperAllocatorDmaMapArray helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaMapArray rteHelperArray
#define _np3_redRteHelperAllocatorDmaMapArray rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorDmaMapArray outVolatilePointer
#define _np5_redRteHelperAllocatorDmaMapArray outStatuses
#define _np6_redRteHelperAllocatorDmaMapArray optionalFile
#define _np7_redRteHelperAllocatorDmaMapArray optionalLine
#define _np8_redRteHelperAllocatorDmaMapArray optionalUserData
#define _np9_redRteHelperAllocatorDmaMapArray rteParameters

#define _np1_redRteHelperAllocatorDmaUnmapArray helperAllocatorDma
#define _np2_redRteHelperAllocatorDmaUnmapArray rteHelperArray
#define _np3_redRteHelperAllocatorDmaUnmapArray rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorDmaUnmapArray outStatuses
#define _np5_redRteHelperAllocatorDmaUnmapArray optionalFile
#define _np6_redRteHelperAllocatorDmaUnmapArray optionalLine
#define _np7_redRteHelperAllocatorDmaUnmapArray optionalUserData
#define _np8_redRteHelperAllocatorDmaUnmapArray rteParameters

#define _np1_redRteCreateHelperAllocatorVma rteContext
#define _np2_redRteCreateHelperAllocatorVma outHelperAllocatorVma
#define _np3_redRteCreateHelperAllocatorVma outStatuses
#define _np4_redRteCreateHelperAllocatorVma optionalFile
#define _np5_redRteCreateHelperAllocatorVma optionalLine
#define _np6_redRteCreateHelperAllocatorVma optionalUserData
#define _np7_redRteCreateHelperAllocatorVma rteParameters

#define _np1_redRteDestroyHelperAllocatorVma helperAllocatorVma
#define _np2_redRteDestroyHelperAllocatorVma optionalFile
#define _np3_redRteDestroyHelperAllocatorVma optionalLine
#define _np4_redRteDestroyHelperAllocatorVma optionalUserData
#define _np5_redRteDestroyHelperAllocatorVma rteParameters

#define _np1_redRteHelperAllocatorVmaCreateArray helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaCreateArray arrayInfo
#define _np3_redRteHelperAllocatorVmaCreateArray memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np4_redRteHelperAllocatorVmaCreateArray outRteHelperArray
#define _np5_redRteHelperAllocatorVmaCreateArray outStatuses
#define _np6_redRteHelperAllocatorVmaCreateArray optionalFile
#define _np7_redRteHelperAllocatorVmaCreateArray optionalLine
#define _np8_redRteHelperAllocatorVmaCreateArray optionalUserData
#define _np9_redRteHelperAllocatorVmaCreateArray rteParameters

#define _np1_redRteHelperAllocatorVmaCreateImage helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaCreateImage imageInfo
#define _np3_redRteHelperAllocatorVmaCreateImage memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np4_redRteHelperAllocatorVmaCreateImage outRteHelperImage
#define _np5_redRteHelperAllocatorVmaCreateImage outStatuses
#define _np6_redRteHelperAllocatorVmaCreateImage optionalFile
#define _np7_redRteHelperAllocatorVmaCreateImage optionalLine
#define _np8_redRteHelperAllocatorVmaCreateImage optionalUserData
#define _np9_redRteHelperAllocatorVmaCreateImage rteParameters

#define _np1_redRteHelperAllocatorVmaCreateArraySimple helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaCreateArraySimple arrayBytesCount
#define _np3_redRteHelperAllocatorVmaCreateArraySimple arrayUsageFlags
#define _np4_redRteHelperAllocatorVmaCreateArraySimple memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np5_redRteHelperAllocatorVmaCreateArraySimple outRteHelperArray
#define _np6_redRteHelperAllocatorVmaCreateArraySimple outStatuses
#define _np7_redRteHelperAllocatorVmaCreateArraySimple optionalFile
#define _np8_redRteHelperAllocatorVmaCreateArraySimple optionalLine
#define _np9_redRteHelperAllocatorVmaCreateArraySimple optionalUserData
#define _np10_redRteHelperAllocatorVmaCreateArraySimple rteParameters

#define _np1_redRteHelperAllocatorVmaCreateArraySimpleWithData helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaCreateArraySimpleWithData callsSetToUploadArrayData
#define _np3_redRteHelperAllocatorVmaCreateArraySimpleWithData arrayDataBytesCount
#define _np4_redRteHelperAllocatorVmaCreateArraySimpleWithData arrayData
#define _np5_redRteHelperAllocatorVmaCreateArraySimpleWithData arrayUsageFlags
#define _np6_redRteHelperAllocatorVmaCreateArraySimpleWithData memoryPropertyFlagsSuggestedDefaultValueIsMemoryPropertyDeviceLocalBit
#define _np7_redRteHelperAllocatorVmaCreateArraySimpleWithData outRteHelperArray
#define _np8_redRteHelperAllocatorVmaCreateArraySimpleWithData outStatuses
#define _np9_redRteHelperAllocatorVmaCreateArraySimpleWithData optionalFile
#define _np10_redRteHelperAllocatorVmaCreateArraySimpleWithData optionalLine
#define _np11_redRteHelperAllocatorVmaCreateArraySimpleWithData optionalUserData
#define _np12_redRteHelperAllocatorVmaCreateArraySimpleWithData rteParameters

#define _np1_redRteHelperAllocatorVmaCreateImageSimpleWithData helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaCreateImageSimpleWithData callsSetToUploadImageData
#define _np3_redRteHelperAllocatorVmaCreateImageSimpleWithData imageDataBytesCount
#define _np4_redRteHelperAllocatorVmaCreateImageSimpleWithData imageData
#define _np5_redRteHelperAllocatorVmaCreateImageSimpleWithData imageInfo
#define _np6_redRteHelperAllocatorVmaCreateImageSimpleWithData imageLayoutSuggestedDefaultValueIsImageLayoutGeneral
#define _np7_redRteHelperAllocatorVmaCreateImageSimpleWithData outRteHelperImage
#define _np8_redRteHelperAllocatorVmaCreateImageSimpleWithData outStatuses
#define _np9_redRteHelperAllocatorVmaCreateImageSimpleWithData optionalFile
#define _np10_redRteHelperAllocatorVmaCreateImageSimpleWithData optionalLine
#define _np11_redRteHelperAllocatorVmaCreateImageSimpleWithData optionalUserData
#define _np12_redRteHelperAllocatorVmaCreateImageSimpleWithData rteParameters

#define _np1_redRteHelperAllocatorVmaDestroyArray helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaDestroyArray rteHelperArray
#define _np3_redRteHelperAllocatorVmaDestroyArray rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorVmaDestroyArray outStatuses
#define _np5_redRteHelperAllocatorVmaDestroyArray optionalFile
#define _np6_redRteHelperAllocatorVmaDestroyArray optionalLine
#define _np7_redRteHelperAllocatorVmaDestroyArray optionalUserData
#define _np8_redRteHelperAllocatorVmaDestroyArray rteParameters

#define _np1_redRteHelperAllocatorVmaDestroyImage helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaDestroyImage rteHelperImage
#define _np3_redRteHelperAllocatorVmaDestroyImage rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorVmaDestroyImage outStatuses
#define _np5_redRteHelperAllocatorVmaDestroyImage optionalFile
#define _np6_redRteHelperAllocatorVmaDestroyImage optionalLine
#define _np7_redRteHelperAllocatorVmaDestroyImage optionalUserData
#define _np8_redRteHelperAllocatorVmaDestroyImage rteParameters

#define _np1_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory optionalCpuSignal
#define _np3_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory outStatuses
#define _np4_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory optionalFile
#define _np5_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory optionalLine
#define _np6_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory optionalUserData
#define _np7_redRteHelperAllocatorVmaFinalizeAndReleaseStagingMemory rteParameters

#define _np1_redRteHelperAllocatorVmaFinalizeStagingMemory helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaFinalizeStagingMemory optionalCpuSignal
#define _np3_redRteHelperAllocatorVmaFinalizeStagingMemory outStatuses
#define _np4_redRteHelperAllocatorVmaFinalizeStagingMemory optionalFile
#define _np5_redRteHelperAllocatorVmaFinalizeStagingMemory optionalLine
#define _np6_redRteHelperAllocatorVmaFinalizeStagingMemory optionalUserData
#define _np7_redRteHelperAllocatorVmaFinalizeStagingMemory rteParameters

#define _np1_redRteHelperAllocatorVmaReleaseStagingMemory helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaReleaseStagingMemory outStatuses
#define _np3_redRteHelperAllocatorVmaReleaseStagingMemory optionalFile
#define _np4_redRteHelperAllocatorVmaReleaseStagingMemory optionalLine
#define _np5_redRteHelperAllocatorVmaReleaseStagingMemory optionalUserData
#define _np6_redRteHelperAllocatorVmaReleaseStagingMemory rteParameters

#define _np1_redRteHelperAllocatorVmaMapArray helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaMapArray rteHelperArray
#define _np3_redRteHelperAllocatorVmaMapArray rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorVmaMapArray outVolatilePointer
#define _np5_redRteHelperAllocatorVmaMapArray outStatuses
#define _np6_redRteHelperAllocatorVmaMapArray optionalFile
#define _np7_redRteHelperAllocatorVmaMapArray optionalLine
#define _np8_redRteHelperAllocatorVmaMapArray optionalUserData
#define _np9_redRteHelperAllocatorVmaMapArray rteParameters

#define _np1_redRteHelperAllocatorVmaUnmapArray helperAllocatorVma
#define _np2_redRteHelperAllocatorVmaUnmapArray rteHelperArray
#define _np3_redRteHelperAllocatorVmaUnmapArray rteHelperAllocatorResourceMemory
#define _np4_redRteHelperAllocatorVmaUnmapArray outStatuses
#define _np5_redRteHelperAllocatorVmaUnmapArray optionalFile
#define _np6_redRteHelperAllocatorVmaUnmapArray optionalLine
#define _np7_redRteHelperAllocatorVmaUnmapArray optionalUserData
#define _np8_redRteHelperAllocatorVmaUnmapArray rteParameters

#define _np1_redRteCreateHelperStructs rteContext
#define _np2_redRteCreateHelperStructs outHelperStructs
#define _np3_redRteCreateHelperStructs outStatuses
#define _np4_redRteCreateHelperStructs optionalFile
#define _np5_redRteCreateHelperStructs optionalLine
#define _np6_redRteCreateHelperStructs optionalUserData
#define _np7_redRteCreateHelperStructs rteParameters

#define _np1_redRteDestroyHelperStructs helperStructs
#define _np2_redRteDestroyHelperStructs optionalFile
#define _np3_redRteDestroyHelperStructs optionalLine
#define _np4_redRteDestroyHelperStructs optionalUserData
#define _np5_redRteDestroyHelperStructs rteParameters

#define _np1_redRteHelperStructsSetStructDeclarationMembers helperStructs
#define _np2_redRteHelperStructsSetStructDeclarationMembers structDeclarationMembersCount
#define _np3_redRteHelperStructsSetStructDeclarationMembers structDeclarationMembers
#define _np4_redRteHelperStructsSetStructDeclarationMembers structDeclarationMembersArrayROCount
#define _np5_redRteHelperStructsSetStructDeclarationMembers structDeclarationMembersArrayRO
#define _np6_redRteHelperStructsSetStructDeclarationMembers optionalFile
#define _np7_redRteHelperStructsSetStructDeclarationMembers optionalLine
#define _np8_redRteHelperStructsSetStructDeclarationMembers optionalUserData
#define _np9_redRteHelperStructsSetStructDeclarationMembers rteParameters

#define _np1_redRteHelperStructsAddStructDeclarationMember helperStructs
#define _np2_redRteHelperStructsAddStructDeclarationMember slot
#define _np3_redRteHelperStructsAddStructDeclarationMember type
#define _np4_redRteHelperStructsAddStructDeclarationMember count
#define _np5_redRteHelperStructsAddStructDeclarationMember visibleToStages
#define _np6_redRteHelperStructsAddStructDeclarationMember inlineSampler
#define _np7_redRteHelperStructsAddStructDeclarationMember slotTypeIsArrayRO
#define _np8_redRteHelperStructsAddStructDeclarationMember optionalFile
#define _np9_redRteHelperStructsAddStructDeclarationMember optionalLine
#define _np10_redRteHelperStructsAddStructDeclarationMember optionalUserData
#define _np11_redRteHelperStructsAddStructDeclarationMember rteParameters

#define _np1_redRteHelperStructsSetStructDeclarationMemberFlags helperStructs
#define _np2_redRteHelperStructsSetStructDeclarationMemberFlags slot
#define _np3_redRteHelperStructsSetStructDeclarationMemberFlags descriptorBindingFlags_RequiresApiSupportGreaterThanVkVersion10
#define _np4_redRteHelperStructsSetStructDeclarationMemberFlags optionalFile
#define _np5_redRteHelperStructsSetStructDeclarationMemberFlags optionalLine
#define _np6_redRteHelperStructsSetStructDeclarationMemberFlags optionalUserData
#define _np7_redRteHelperStructsSetStructDeclarationMemberFlags rteParameters

#define _np1_redRteHelperStructsCreateStructDeclaration helperStructs
#define _np2_redRteHelperStructsCreateStructDeclaration descriptorSetLayoutCreateFlags
#define _np3_redRteHelperStructsCreateStructDeclaration apiSupport
#define _np4_redRteHelperStructsCreateStructDeclaration outStructDeclaration
#define _np5_redRteHelperStructsCreateStructDeclaration outStatuses
#define _np6_redRteHelperStructsCreateStructDeclaration optionalFile
#define _np7_redRteHelperStructsCreateStructDeclaration optionalLine
#define _np8_redRteHelperStructsCreateStructDeclaration optionalUserData
#define _np9_redRteHelperStructsCreateStructDeclaration rteParameters

#define _np1_redRteHelperStructsCreateStructsMemory helperStructs
#define _np2_redRteHelperStructsCreateStructsMemory allocateStructsCount
#define _np3_redRteHelperStructsCreateStructsMemory outStructsMemory
#define _np4_redRteHelperStructsCreateStructsMemory outStatuses
#define _np5_redRteHelperStructsCreateStructsMemory optionalFile
#define _np6_redRteHelperStructsCreateStructsMemory optionalLine
#define _np7_redRteHelperStructsCreateStructsMemory optionalUserData
#define _np8_redRteHelperStructsCreateStructsMemory rteParameters

#define _np1_redRteHelperStructsGetStruct helperStructs
#define _np2_redRteHelperStructsGetStruct structIndex
#define _np3_redRteHelperStructsGetStruct optionalFile
#define _np4_redRteHelperStructsGetStruct optionalLine
#define _np5_redRteHelperStructsGetStruct optionalUserData
#define _np6_redRteHelperStructsGetStruct rteParameters

#define _np1_redRteHelperStructsGetStructsCount helperStructs
#define _np2_redRteHelperStructsGetStructsCount optionalFile
#define _np3_redRteHelperStructsGetStructsCount optionalLine
#define _np4_redRteHelperStructsGetStructsCount optionalUserData
#define _np5_redRteHelperStructsGetStructsCount rteParameters

#define _np1_redRteHelperStructsGetStructs helperStructs
#define _np2_redRteHelperStructsGetStructs optionalFile
#define _np3_redRteHelperStructsGetStructs optionalLine
#define _np4_redRteHelperStructsGetStructs optionalUserData
#define _np5_redRteHelperStructsGetStructs rteParameters

#define _np1_redRteHelperStructsGetStructDeclarationMembersCount helperStructs
#define _np2_redRteHelperStructsGetStructDeclarationMembersCount optionalFile
#define _np3_redRteHelperStructsGetStructDeclarationMembersCount optionalLine
#define _np4_redRteHelperStructsGetStructDeclarationMembersCount optionalUserData
#define _np5_redRteHelperStructsGetStructDeclarationMembersCount rteParameters

#define _np1_redRteHelperStructsGetStructDeclarationMembers helperStructs
#define _np2_redRteHelperStructsGetStructDeclarationMembers optionalFile
#define _np3_redRteHelperStructsGetStructDeclarationMembers optionalLine
#define _np4_redRteHelperStructsGetStructDeclarationMembers optionalUserData
#define _np5_redRteHelperStructsGetStructDeclarationMembers rteParameters

#define _np1_redRteHelperStructsDestroyStructDeclaration helperStructs
#define _np2_redRteHelperStructsDestroyStructDeclaration optionalFile
#define _np3_redRteHelperStructsDestroyStructDeclaration optionalLine
#define _np4_redRteHelperStructsDestroyStructDeclaration optionalUserData
#define _np5_redRteHelperStructsDestroyStructDeclaration rteParameters

#define _np1_redRteHelperStructsDestroyStructsMemory helperStructs
#define _np2_redRteHelperStructsDestroyStructsMemory optionalFile
#define _np3_redRteHelperStructsDestroyStructsMemory optionalLine
#define _np4_redRteHelperStructsDestroyStructsMemory optionalUserData
#define _np5_redRteHelperStructsDestroyStructsMemory rteParameters

#define _np1_redRteHelperStructsClear helperStructs
#define _np2_redRteHelperStructsClear optionalFile
#define _np3_redRteHelperStructsClear optionalLine
#define _np4_redRteHelperStructsClear optionalUserData
#define _np5_redRteHelperStructsClear rteParameters

#define _np1_redRteCreateRayTracingBuilder rteContext
#define _np2_redRteCreateRayTracingBuilder rteHandleHelperAllocator
#define _np3_redRteCreateRayTracingBuilder queueFamilyIndex
#define _np4_redRteCreateRayTracingBuilder outRayTracingBuilder
#define _np5_redRteCreateRayTracingBuilder outStatuses
#define _np6_redRteCreateRayTracingBuilder optionalFile
#define _np7_redRteCreateRayTracingBuilder optionalLine
#define _np8_redRteCreateRayTracingBuilder optionalUserData
#define _np9_redRteCreateRayTracingBuilder rteParameters

#define _np1_redRteDestroyRayTracingBuilder rayTracingBuilder
#define _np2_redRteDestroyRayTracingBuilder optionalFile
#define _np3_redRteDestroyRayTracingBuilder optionalLine
#define _np4_redRteDestroyRayTracingBuilder optionalUserData
#define _np5_redRteDestroyRayTracingBuilder rteParameters

#define _np1_redRteRayTracingBuilderBuildBlas rayTracingBuilder
#define _np2_redRteRayTracingBuilderBuildBlas blasInputsCount
#define _np3_redRteRayTracingBuilderBuildBlas blasInputs
#define _np4_redRteRayTracingBuilderBuildBlas buildAccelerationStructureFlagsSuggestedDefaultValueIsBuildAccelerationStructurePreferFastTraceBit
#define _np5_redRteRayTracingBuilderBuildBlas outStatuses
#define _np6_redRteRayTracingBuilderBuildBlas optionalFile
#define _np7_redRteRayTracingBuilderBuildBlas optionalLine
#define _np8_redRteRayTracingBuilderBuildBlas optionalUserData
#define _np9_redRteRayTracingBuilderBuildBlas rteParameters

#define _np1_redRteRayTracingBuilderGetBlasGpuAddress rayTracingBuilder
#define _np2_redRteRayTracingBuilderGetBlasGpuAddress blasIndex
#define _np3_redRteRayTracingBuilderGetBlasGpuAddress optionalFile
#define _np4_redRteRayTracingBuilderGetBlasGpuAddress optionalLine
#define _np5_redRteRayTracingBuilderGetBlasGpuAddress optionalUserData
#define _np6_redRteRayTracingBuilderGetBlasGpuAddress rteParameters

#define _np1_redRteRayTracingBuilderBuildTlas rayTracingBuilder
#define _np2_redRteRayTracingBuilderBuildTlas instancesCount
#define _np3_redRteRayTracingBuilderBuildTlas instances
#define _np4_redRteRayTracingBuilderBuildTlas buildAccelerationStructureFlagsSuggestedDefaultValueIsBuildAccelerationStructurePreferFastTraceBit
#define _np5_redRteRayTracingBuilderBuildTlas update
#define _np6_redRteRayTracingBuilderBuildTlas outStatuses
#define _np7_redRteRayTracingBuilderBuildTlas optionalFile
#define _np8_redRteRayTracingBuilderBuildTlas optionalLine
#define _np9_redRteRayTracingBuilderBuildTlas optionalUserData
#define _np10_redRteRayTracingBuilderBuildTlas rteParameters

#define _np1_redRteRayTracingBuilderGetTlas rayTracingBuilder
#define _np2_redRteRayTracingBuilderGetTlas optionalFile
#define _np3_redRteRayTracingBuilderGetTlas optionalLine
#define _np4_redRteRayTracingBuilderGetTlas optionalUserData
#define _np5_redRteRayTracingBuilderGetTlas rteParameters

#define _np1_redRteRayTracingBuilderUpdateBlas rayTracingBuilder
#define _np2_redRteRayTracingBuilderUpdateBlas blasIndex
#define _np3_redRteRayTracingBuilderUpdateBlas blasInput
#define _np4_redRteRayTracingBuilderUpdateBlas buildAccelerationStructureFlagsSuggestedDefaultValueIsBuildAccelerationStructurePreferFastTraceBit
#define _np5_redRteRayTracingBuilderUpdateBlas outStatuses
#define _np6_redRteRayTracingBuilderUpdateBlas optionalFile
#define _np7_redRteRayTracingBuilderUpdateBlas optionalLine
#define _np8_redRteRayTracingBuilderUpdateBlas optionalUserData
#define _np9_redRteRayTracingBuilderUpdateBlas rteParameters

#define _np1_redRteCreateDeferredOperation rteContext
#define _np2_redRteCreateDeferredOperation outDeferredOperation
#define _np3_redRteCreateDeferredOperation outStatuses
#define _np4_redRteCreateDeferredOperation optionalFile
#define _np5_redRteCreateDeferredOperation optionalLine
#define _np6_redRteCreateDeferredOperation optionalUserData
#define _np7_redRteCreateDeferredOperation rteParameters

#define _np1_redRteDestroyDeferredOperation rteContext
#define _np2_redRteDestroyDeferredOperation deferredOperation
#define _np3_redRteDestroyDeferredOperation optionalFile
#define _np4_redRteDestroyDeferredOperation optionalLine
#define _np5_redRteDestroyDeferredOperation optionalUserData
#define _np6_redRteDestroyDeferredOperation rteParameters

#define _np1_redRteDeferredOperationGetMaxConcurrency rteContext
#define _np2_redRteDeferredOperationGetMaxConcurrency deferredOperation
#define _np3_redRteDeferredOperationGetMaxConcurrency optionalFile
#define _np4_redRteDeferredOperationGetMaxConcurrency optionalLine
#define _np5_redRteDeferredOperationGetMaxConcurrency optionalUserData
#define _np6_redRteDeferredOperationGetMaxConcurrency rteParameters

#define _np1_redRteDeferredOperationGetStatus rteContext
#define _np2_redRteDeferredOperationGetStatus deferredOperation
#define _np3_redRteDeferredOperationGetStatus optionalFile
#define _np4_redRteDeferredOperationGetStatus optionalLine
#define _np5_redRteDeferredOperationGetStatus optionalUserData
#define _np6_redRteDeferredOperationGetStatus rteParameters

#define _np1_redRteDeferredOperationJoin rteContext
#define _np2_redRteDeferredOperationJoin deferredOperation
#define _np3_redRteDeferredOperationJoin optionalFile
#define _np4_redRteDeferredOperationJoin optionalLine
#define _np5_redRteDeferredOperationJoin optionalUserData
#define _np6_redRteDeferredOperationJoin rteParameters

#define _np1_redRteCreateProcedureRayTracing rteContext
#define _np2_redRteCreateProcedureRayTracing deferredOperation
#define _np3_redRteCreateProcedureRayTracing procedureCache
#define _np4_redRteCreateProcedureRayTracing state
#define _np5_redRteCreateProcedureRayTracing outProcedure
#define _np6_redRteCreateProcedureRayTracing outStatuses
#define _np7_redRteCreateProcedureRayTracing optionalFile
#define _np8_redRteCreateProcedureRayTracing optionalLine
#define _np9_redRteCreateProcedureRayTracing optionalUserData
#define _np10_redRteCreateProcedureRayTracing rteParameters

#define _np1_redRteProcedureRayTracingGetGroupCaptureReplayHandles rteContext
#define _np2_redRteProcedureRayTracingGetGroupCaptureReplayHandles procedureRayTracing
#define _np3_redRteProcedureRayTracingGetGroupCaptureReplayHandles groupIndexFirst
#define _np4_redRteProcedureRayTracingGetGroupCaptureReplayHandles groupIndexCount
#define _np5_redRteProcedureRayTracingGetGroupCaptureReplayHandles dataBytesCount
#define _np6_redRteProcedureRayTracingGetGroupCaptureReplayHandles data
#define _np7_redRteProcedureRayTracingGetGroupCaptureReplayHandles optionalFile
#define _np8_redRteProcedureRayTracingGetGroupCaptureReplayHandles optionalLine
#define _np9_redRteProcedureRayTracingGetGroupCaptureReplayHandles optionalUserData
#define _np10_redRteProcedureRayTracingGetGroupCaptureReplayHandles rteParameters

#define _np1_redRteProcedureRayTracingGetGroupStackBytesCount rteContext
#define _np2_redRteProcedureRayTracingGetGroupStackBytesCount procedureRayTracing
#define _np3_redRteProcedureRayTracingGetGroupStackBytesCount groupIndex
#define _np4_redRteProcedureRayTracingGetGroupStackBytesCount groupStage
#define _np5_redRteProcedureRayTracingGetGroupStackBytesCount optionalFile
#define _np6_redRteProcedureRayTracingGetGroupStackBytesCount optionalLine
#define _np7_redRteProcedureRayTracingGetGroupStackBytesCount optionalUserData
#define _np8_redRteProcedureRayTracingGetGroupStackBytesCount rteParameters

#define _np1_redRteCallProcedureRayTracing calls
#define _np2_redRteCallProcedureRayTracing rteContext
#define _np3_redRteCallProcedureRayTracing shaderBindingTableRayGeneration
#define _np4_redRteCallProcedureRayTracing shaderBindingTableMiss
#define _np5_redRteCallProcedureRayTracing shaderBindingTableHit
#define _np6_redRteCallProcedureRayTracing shaderBindingTableCallable
#define _np7_redRteCallProcedureRayTracing threadsCountX
#define _np8_redRteCallProcedureRayTracing threadsCountY
#define _np9_redRteCallProcedureRayTracing threadsCountZ
#define _np10_redRteCallProcedureRayTracing optionalFile
#define _np11_redRteCallProcedureRayTracing optionalLine
#define _np12_redRteCallProcedureRayTracing optionalUserData
#define _np13_redRteCallProcedureRayTracing rteParameters

#define _np1_redRteCallProcedureIndirect calls
#define _np2_redRteCallProcedureIndirect rteContext
#define _np3_redRteCallProcedureIndirect array
#define _np4_redRteCallProcedureIndirect arrayBytesFirst
#define _np5_redRteCallProcedureIndirect count
#define _np6_redRteCallProcedureIndirect bytesStride
#define _np7_redRteCallProcedureIndirect optionalFile
#define _np8_redRteCallProcedureIndirect optionalLine
#define _np9_redRteCallProcedureIndirect optionalUserData
#define _np10_redRteCallProcedureIndirect rteParameters

#define _np1_redRteCallProcedureIndexedIndirect calls
#define _np2_redRteCallProcedureIndexedIndirect rteContext
#define _np3_redRteCallProcedureIndexedIndirect array
#define _np4_redRteCallProcedureIndexedIndirect arrayBytesFirst
#define _np5_redRteCallProcedureIndexedIndirect count
#define _np6_redRteCallProcedureIndexedIndirect bytesStride
#define _np7_redRteCallProcedureIndexedIndirect optionalFile
#define _np8_redRteCallProcedureIndexedIndirect optionalLine
#define _np9_redRteCallProcedureIndexedIndirect optionalUserData
#define _np10_redRteCallProcedureIndexedIndirect rteParameters

#define _np1_redRteCallProcedureComputeIndirect calls
#define _np2_redRteCallProcedureComputeIndirect rteContext
#define _np3_redRteCallProcedureComputeIndirect array
#define _np4_redRteCallProcedureComputeIndirect arrayBytesFirst
#define _np5_redRteCallProcedureComputeIndirect optionalFile
#define _np6_redRteCallProcedureComputeIndirect optionalLine
#define _np7_redRteCallProcedureComputeIndirect optionalUserData
#define _np8_redRteCallProcedureComputeIndirect rteParameters

#define _np1_redRteCallProcedureRayTracingIndirect calls
#define _np2_redRteCallProcedureRayTracingIndirect rteContext
#define _np3_redRteCallProcedureRayTracingIndirect shaderBindingTableRayGeneration
#define _np4_redRteCallProcedureRayTracingIndirect shaderBindingTableMiss
#define _np5_redRteCallProcedureRayTracingIndirect shaderBindingTableHit
#define _np6_redRteCallProcedureRayTracingIndirect shaderBindingTableCallable
#define _np7_redRteCallProcedureRayTracingIndirect gpuAddress
#define _np8_redRteCallProcedureRayTracingIndirect optionalFile
#define _np9_redRteCallProcedureRayTracingIndirect optionalLine
#define _np10_redRteCallProcedureRayTracingIndirect optionalUserData
#define _np11_redRteCallProcedureRayTracingIndirect rteParameters

#define _np1_redRteCallSetProcedureRayTracingStackBytesCount calls
#define _np2_redRteCallSetProcedureRayTracingStackBytesCount rteContext
#define _np3_redRteCallSetProcedureRayTracingStackBytesCount stackBytesCount
#define _np4_redRteCallSetProcedureRayTracingStackBytesCount optionalFile
#define _np5_redRteCallSetProcedureRayTracingStackBytesCount optionalLine
#define _np6_redRteCallSetProcedureRayTracingStackBytesCount optionalUserData
#define _np7_redRteCallSetProcedureRayTracingStackBytesCount rteParameters

#define _np1_redRteCreateHelperShaderBindingTable rteContext
#define _np2_redRteCreateHelperShaderBindingTable rteHandleHelperAllocator
#define _np3_redRteCreateHelperShaderBindingTable queueFamilyIndex
#define _np4_redRteCreateHelperShaderBindingTable outHelperShaderBindingTable
#define _np5_redRteCreateHelperShaderBindingTable outStatuses
#define _np6_redRteCreateHelperShaderBindingTable optionalFile
#define _np7_redRteCreateHelperShaderBindingTable optionalLine
#define _np8_redRteCreateHelperShaderBindingTable optionalUserData
#define _np9_redRteCreateHelperShaderBindingTable rteParameters

#define _np1_redRteDestroyHelperShaderBindingTable helperShaderBindingTable
#define _np2_redRteDestroyHelperShaderBindingTable optionalFile
#define _np3_redRteDestroyHelperShaderBindingTable optionalLine
#define _np4_redRteDestroyHelperShaderBindingTable optionalUserData
#define _np5_redRteDestroyHelperShaderBindingTable rteParameters

#define _np1_redRteHelperShaderBindingTableCreate helperShaderBindingTable
#define _np2_redRteHelperShaderBindingTableCreate procedureRayTracing
#define _np3_redRteHelperShaderBindingTableCreate procedureRayTracingState
#define _np4_redRteHelperShaderBindingTableCreate optionalFile
#define _np5_redRteHelperShaderBindingTableCreate optionalLine
#define _np6_redRteHelperShaderBindingTableCreate optionalUserData
#define _np7_redRteHelperShaderBindingTableCreate rteParameters

#define _np1_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange helperShaderBindingTable
#define _np2_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange outShaderBindingTableRayGeneration
#define _np3_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange outShaderBindingTableMiss
#define _np4_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange outShaderBindingTableHit
#define _np5_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange outShaderBindingTableCallable
#define _np6_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange optionalFile
#define _np7_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange optionalLine
#define _np8_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange optionalUserData
#define _np9_redRteHelperShaderBindingTableGetGpuAddressStrideAndRange rteParameters

#define _np1_redRteGetInstanceProcAddr optionalFile
#define _np2_redRteGetInstanceProcAddr optionalLine
#define _np3_redRteGetInstanceProcAddr optionalUserData
#define _np4_redRteGetInstanceProcAddr rteParameters

#define _np1_redRteCreateContextFromRteContext rteContext
#define _np2_redRteCreateContextFromRteContext malloc
#define _np3_redRteCreateContextFromRteContext free
#define _np4_redRteCreateContextFromRteContext optionalMallocTagged
#define _np5_redRteCreateContextFromRteContext optionalFreeTagged
#define _np6_redRteCreateContextFromRteContext debugCallback
#define _np7_redRteCreateContextFromRteContext sdkVersion
#define _np8_redRteCreateContextFromRteContext sdkExtensionsCount
#define _np9_redRteCreateContextFromRteContext sdkExtensions
#define _np10_redRteCreateContextFromRteContext optionalProgramName
#define _np11_redRteCreateContextFromRteContext optionalProgramVersion
#define _np12_redRteCreateContextFromRteContext optionalEngineName
#define _np13_redRteCreateContextFromRteContext optionalEngineVersion
#define _np14_redRteCreateContextFromRteContext optionalSettings
#define _np15_redRteCreateContextFromRteContext outContext
#define _np16_redRteCreateContextFromRteContext outStatuses
#define _np17_redRteCreateContextFromRteContext optionalFile
#define _np18_redRteCreateContextFromRteContext optionalLine
#define _np19_redRteCreateContextFromRteContext optionalUserData
#define _np20_redRteCreateContextFromRteContext rteParameters

#define _np1_redRteCreateHelperAppWindow callbacks
#define _np2_redRteCreateHelperAppWindow initialWindowWidth
#define _np3_redRteCreateHelperAppWindow initialWindowHeight
#define _np4_redRteCreateHelperAppWindow initialIsVsyncEnabled
#define _np5_redRteCreateHelperAppWindow initialViewportClearColorR
#define _np6_redRteCreateHelperAppWindow initialViewportClearColorG
#define _np7_redRteCreateHelperAppWindow initialViewportClearColorB
#define _np8_redRteCreateHelperAppWindow initialViewportClearColorA
#define _np9_redRteCreateHelperAppWindow optionalProgramName
#define _np10_redRteCreateHelperAppWindow optionalEngineName
#define _np11_redRteCreateHelperAppWindow rteCreateContextParameters
#define _np12_redRteCreateHelperAppWindow outHelperAppWindow
#define _np13_redRteCreateHelperAppWindow outStatuses
#define _np14_redRteCreateHelperAppWindow optionalFile
#define _np15_redRteCreateHelperAppWindow optionalLine
#define _np16_redRteCreateHelperAppWindow optionalUserData
#define _np17_redRteCreateHelperAppWindow rteParameters

#define _np1_redRteDestroyHelperAppWindow helperAppWindow
#define _np2_redRteDestroyHelperAppWindow optionalFile
#define _np3_redRteDestroyHelperAppWindow optionalLine
#define _np4_redRteDestroyHelperAppWindow optionalUserData
#define _np5_redRteDestroyHelperAppWindow rteParameters

#define _np1_redRteHelperAppWindowRun helperAppWindow
#define _np2_redRteHelperAppWindowRun optionalFile
#define _np3_redRteHelperAppWindowRun optionalLine
#define _np4_redRteHelperAppWindowRun optionalUserData
#define _np5_redRteHelperAppWindowRun rteParameters

#define _np1_redRteHelperAppWindowClose helperAppWindow
#define _np2_redRteHelperAppWindowClose optionalFile
#define _np3_redRteHelperAppWindowClose optionalLine
#define _np4_redRteHelperAppWindowClose optionalUserData
#define _np5_redRteHelperAppWindowClose rteParameters

#define _np1_redRteHelperAppWindowSetViewport helperAppWindow
#define _np2_redRteHelperAppWindowSetViewport calls
#define _np3_redRteHelperAppWindowSetViewport optionalFile
#define _np4_redRteHelperAppWindowSetViewport optionalLine
#define _np5_redRteHelperAppWindowSetViewport optionalUserData
#define _np6_redRteHelperAppWindowSetViewport rteParameters

#define _np1_redRteHelperAppWindowIsVsyncEnabled helperAppWindow
#define _np2_redRteHelperAppWindowIsVsyncEnabled optionalFile
#define _np3_redRteHelperAppWindowIsVsyncEnabled optionalLine
#define _np4_redRteHelperAppWindowIsVsyncEnabled optionalUserData
#define _np5_redRteHelperAppWindowIsVsyncEnabled rteParameters

#define _np1_redRteHelperAppWindowSetVsyncEnabled helperAppWindow
#define _np2_redRteHelperAppWindowSetVsyncEnabled enableVsync
#define _np3_redRteHelperAppWindowSetVsyncEnabled optionalFile
#define _np4_redRteHelperAppWindowSetVsyncEnabled optionalLine
#define _np5_redRteHelperAppWindowSetVsyncEnabled optionalUserData
#define _np6_redRteHelperAppWindowSetVsyncEnabled rteParameters

#define _np1_redRteHelperAppWindowSetViewportClearColor helperAppWindow
#define _np2_redRteHelperAppWindowSetViewportClearColor viewportClearColorR
#define _np3_redRteHelperAppWindowSetViewportClearColor viewportClearColorG
#define _np4_redRteHelperAppWindowSetViewportClearColor viewportClearColorB
#define _np5_redRteHelperAppWindowSetViewportClearColor viewportClearColorA
#define _np6_redRteHelperAppWindowSetViewportClearColor optionalFile
#define _np7_redRteHelperAppWindowSetViewportClearColor optionalLine
#define _np8_redRteHelperAppWindowSetViewportClearColor optionalUserData
#define _np9_redRteHelperAppWindowSetViewportClearColor rteParameters

#define _np1_redRteHelperAppWindowAddWaitSemaphore helperAppWindow
#define _np2_redRteHelperAppWindowAddWaitSemaphore vkSemaphoreSubmitInfoKHR
#define _np3_redRteHelperAppWindowAddWaitSemaphore optionalFile
#define _np4_redRteHelperAppWindowAddWaitSemaphore optionalLine
#define _np5_redRteHelperAppWindowAddWaitSemaphore optionalUserData
#define _np6_redRteHelperAppWindowAddWaitSemaphore rteParameters

#define _np1_redRteHelperAppWindowTempCallsCreateAndSet helperAppWindow
#define _np2_redRteHelperAppWindowTempCallsCreateAndSet optionalFile
#define _np3_redRteHelperAppWindowTempCallsCreateAndSet optionalLine
#define _np4_redRteHelperAppWindowTempCallsCreateAndSet optionalUserData
#define _np5_redRteHelperAppWindowTempCallsCreateAndSet rteParameters

#define _np1_redRteHelperAppWindowTempCallsEndSubmitWaitAndDestroy helperAppWindow
#define _np2_redRteHelperAppWindowTempCallsEndSubmitWaitAndDestroy tempCalls
#define _np3_redRteHelperAppWindowTempCallsEndSubmitWaitAndDestroy optionalFile
#define _np4_redRteHelperAppWindowTempCallsEndSubmitWaitAndDestroy optionalLine
#define _np5_redRteHelperAppWindowTempCallsEndSubmitWaitAndDestroy optionalUserData
#define _np6_redRteHelperAppWindowTempCallsEndSubmitWaitAndDestroy rteParameters

#define _np1_redRteHelperAppWindowOnFileDrop helperAppWindow
#define _np2_redRteHelperAppWindowOnFileDrop filename
#define _np3_redRteHelperAppWindowOnFileDrop optionalFile
#define _np4_redRteHelperAppWindowOnFileDrop optionalLine
#define _np5_redRteHelperAppWindowOnFileDrop optionalUserData
#define _np6_redRteHelperAppWindowOnFileDrop rteParameters

#define _np1_redRteHelperAppWindowGetRteContext helperAppWindow
#define _np2_redRteHelperAppWindowGetRteContext optionalFile
#define _np3_redRteHelperAppWindowGetRteContext optionalLine
#define _np4_redRteHelperAppWindowGetRteContext optionalUserData
#define _np5_redRteHelperAppWindowGetRteContext rteParameters

#define _np1_redRteHelperAppWindowGetGlfwWindow helperAppWindow
#define _np2_redRteHelperAppWindowGetGlfwWindow optionalFile
#define _np3_redRteHelperAppWindowGetGlfwWindow optionalLine
#define _np4_redRteHelperAppWindowGetGlfwWindow optionalUserData
#define _np5_redRteHelperAppWindowGetGlfwWindow rteParameters

#define _np1_redRteHelperAppWindowGetViewportWidth helperAppWindow
#define _np2_redRteHelperAppWindowGetViewportWidth optionalFile
#define _np3_redRteHelperAppWindowGetViewportWidth optionalLine
#define _np4_redRteHelperAppWindowGetViewportWidth optionalUserData
#define _np5_redRteHelperAppWindowGetViewportWidth rteParameters

#define _np1_redRteHelperAppWindowGetViewportHeight helperAppWindow
#define _np2_redRteHelperAppWindowGetViewportHeight optionalFile
#define _np3_redRteHelperAppWindowGetViewportHeight optionalLine
#define _np4_redRteHelperAppWindowGetViewportHeight optionalUserData
#define _np5_redRteHelperAppWindowGetViewportHeight rteParameters

#define _np1_redRteHelperAppWindowGetWindowWidth helperAppWindow
#define _np2_redRteHelperAppWindowGetWindowWidth optionalFile
#define _np3_redRteHelperAppWindowGetWindowWidth optionalLine
#define _np4_redRteHelperAppWindowGetWindowWidth optionalUserData
#define _np5_redRteHelperAppWindowGetWindowWidth rteParameters

#define _np1_redRteHelperAppWindowGetWindowHeight helperAppWindow
#define _np2_redRteHelperAppWindowGetWindowHeight optionalFile
#define _np3_redRteHelperAppWindowGetWindowHeight optionalLine
#define _np4_redRteHelperAppWindowGetWindowHeight optionalUserData
#define _np5_redRteHelperAppWindowGetWindowHeight rteParameters

#define _np1_redRteHelperAppWindowGetImGuiImplVulkanHWindowData helperAppWindow
#define _np2_redRteHelperAppWindowGetImGuiImplVulkanHWindowData optionalFile
#define _np3_redRteHelperAppWindowGetImGuiImplVulkanHWindowData optionalLine
#define _np4_redRteHelperAppWindowGetImGuiImplVulkanHWindowData optionalUserData
#define _np5_redRteHelperAppWindowGetImGuiImplVulkanHWindowData rteParameters

#define _np1_redRteCreateHelperGBuffer rteContext
#define _np2_redRteCreateHelperGBuffer rteHandleHelperAllocator
#define _np3_redRteCreateHelperGBuffer width
#define _np4_redRteCreateHelperGBuffer height
#define _np5_redRteCreateHelperGBuffer colorFormatsCount
#define _np6_redRteCreateHelperGBuffer colorFormats
#define _np7_redRteCreateHelperGBuffer depthFormat
#define _np8_redRteCreateHelperGBuffer outHelperGBuffer
#define _np9_redRteCreateHelperGBuffer outStatuses
#define _np10_redRteCreateHelperGBuffer optionalFile
#define _np11_redRteCreateHelperGBuffer optionalLine
#define _np12_redRteCreateHelperGBuffer optionalUserData
#define _np13_redRteCreateHelperGBuffer rteParameters

#define _np1_redRteDestroyHelperGBuffer helperGBuffer
#define _np2_redRteDestroyHelperGBuffer optionalFile
#define _np3_redRteDestroyHelperGBuffer optionalLine
#define _np4_redRteDestroyHelperGBuffer optionalUserData
#define _np5_redRteDestroyHelperGBuffer rteParameters

#define _np1_redRteHelperGBufferGetStruct helperGBuffer
#define _np2_redRteHelperGBufferGetStruct index
#define _np3_redRteHelperGBufferGetStruct optionalFile
#define _np4_redRteHelperGBufferGetStruct optionalLine
#define _np5_redRteHelperGBufferGetStruct optionalUserData
#define _np6_redRteHelperGBufferGetStruct rteParameters

#define _np1_redRteHelperGBufferGetWidth helperGBuffer
#define _np2_redRteHelperGBufferGetWidth optionalFile
#define _np3_redRteHelperGBufferGetWidth optionalLine
#define _np4_redRteHelperGBufferGetWidth optionalUserData
#define _np5_redRteHelperGBufferGetWidth rteParameters

#define _np1_redRteHelperGBufferGetHeight helperGBuffer
#define _np2_redRteHelperGBufferGetHeight optionalFile
#define _np3_redRteHelperGBufferGetHeight optionalLine
#define _np4_redRteHelperGBufferGetHeight optionalUserData
#define _np5_redRteHelperGBufferGetHeight rteParameters

#define _np1_redRteHelperGBufferGetColorImage helperGBuffer
#define _np2_redRteHelperGBufferGetColorImage index
#define _np3_redRteHelperGBufferGetColorImage optionalFile
#define _np4_redRteHelperGBufferGetColorImage optionalLine
#define _np5_redRteHelperGBufferGetColorImage optionalUserData
#define _np6_redRteHelperGBufferGetColorImage rteParameters

#define _np1_redRteHelperGBufferGetDepthImage helperGBuffer
#define _np2_redRteHelperGBufferGetDepthImage optionalFile
#define _np3_redRteHelperGBufferGetDepthImage optionalLine
#define _np4_redRteHelperGBufferGetDepthImage optionalUserData
#define _np5_redRteHelperGBufferGetDepthImage rteParameters

#define _np1_redRteHelperGBufferGetStructMemberTexture helperGBuffer
#define _np2_redRteHelperGBufferGetStructMemberTexture index
#define _np3_redRteHelperGBufferGetStructMemberTexture outStructMemberTexture
#define _np4_redRteHelperGBufferGetStructMemberTexture optionalFile
#define _np5_redRteHelperGBufferGetStructMemberTexture optionalLine
#define _np6_redRteHelperGBufferGetStructMemberTexture optionalUserData
#define _np7_redRteHelperGBufferGetStructMemberTexture rteParameters

#define _np1_redRteHelperGBufferGetColorTexture helperGBuffer
#define _np2_redRteHelperGBufferGetColorTexture index
#define _np3_redRteHelperGBufferGetColorTexture optionalFile
#define _np4_redRteHelperGBufferGetColorTexture optionalLine
#define _np5_redRteHelperGBufferGetColorTexture optionalUserData
#define _np6_redRteHelperGBufferGetColorTexture rteParameters

#define _np1_redRteHelperGBufferGetDepthTexture helperGBuffer
#define _np2_redRteHelperGBufferGetDepthTexture optionalFile
#define _np3_redRteHelperGBufferGetDepthTexture optionalLine
#define _np4_redRteHelperGBufferGetDepthTexture optionalUserData
#define _np5_redRteHelperGBufferGetDepthTexture rteParameters

#define _np1_redRteHelperGBufferGetColorFormat helperGBuffer
#define _np2_redRteHelperGBufferGetColorFormat index
#define _np3_redRteHelperGBufferGetColorFormat optionalFile
#define _np4_redRteHelperGBufferGetColorFormat optionalLine
#define _np5_redRteHelperGBufferGetColorFormat optionalUserData
#define _np6_redRteHelperGBufferGetColorFormat rteParameters

#define _np1_redRteHelperGBufferGetDepthFormat helperGBuffer
#define _np2_redRteHelperGBufferGetDepthFormat optionalFile
#define _np3_redRteHelperGBufferGetDepthFormat optionalLine
#define _np4_redRteHelperGBufferGetDepthFormat optionalUserData
#define _np5_redRteHelperGBufferGetDepthFormat rteParameters

#define _np1_redRteHelperGBufferGetAspectRatio helperGBuffer
#define _np2_redRteHelperGBufferGetAspectRatio optionalFile
#define _np3_redRteHelperGBufferGetAspectRatio optionalLine
#define _np4_redRteHelperGBufferGetAspectRatio optionalUserData
#define _np5_redRteHelperGBufferGetAspectRatio rteParameters

#define _np1_redRteGpuWaitIdle rteContext
#define _np2_redRteGpuWaitIdle optionalFile
#define _np3_redRteGpuWaitIdle optionalLine
#define _np4_redRteGpuWaitIdle optionalUserData
#define _np5_redRteGpuWaitIdle rteParameters

#define _np1_redRteQueueWaitIdle rteContext
#define _np2_redRteQueueWaitIdle queue
#define _np3_redRteQueueWaitIdle optionalFile
#define _np4_redRteQueueWaitIdle optionalLine
#define _np5_redRteQueueWaitIdle optionalUserData
#define _np6_redRteQueueWaitIdle rteParameters

#define _np1_redRteArrayGetMemoryRequirements rteContext
#define _np2_redRteArrayGetMemoryRequirements inoutArray
#define _np3_redRteArrayGetMemoryRequirements optionalFile
#define _np4_redRteArrayGetMemoryRequirements optionalLine
#define _np5_redRteArrayGetMemoryRequirements optionalUserData
#define _np6_redRteArrayGetMemoryRequirements rteParameters

#define _np1_redRteImageGetMemoryRequirements rteContext
#define _np2_redRteImageGetMemoryRequirements inoutImage
#define _np3_redRteImageGetMemoryRequirements optionalFile
#define _np4_redRteImageGetMemoryRequirements optionalLine
#define _np5_redRteImageGetMemoryRequirements optionalUserData
#define _np6_redRteImageGetMemoryRequirements rteParameters

#define _np1_redRteCallUsageAliasOrderBarrier calls
#define _np2_redRteCallUsageAliasOrderBarrier rteContext
#define _np3_redRteCallUsageAliasOrderBarrier arrayUsagesCount
#define _np4_redRteCallUsageAliasOrderBarrier arrayUsages
#define _np5_redRteCallUsageAliasOrderBarrier imageUsagesCount
#define _np6_redRteCallUsageAliasOrderBarrier imageUsages
#define _np7_redRteCallUsageAliasOrderBarrier aliasesCount
#define _np8_redRteCallUsageAliasOrderBarrier aliases
#define _np9_redRteCallUsageAliasOrderBarrier ordersCount
#define _np10_redRteCallUsageAliasOrderBarrier orders
#define _np11_redRteCallUsageAliasOrderBarrier dependencyFlags

