#pragma once

#define _np1_redXRteArrayGetGpuAddress array
#define _np2_redXRteArrayGetGpuAddress optionalFile
#define _np3_redXRteArrayGetGpuAddress optionalLine
#define _np4_redXRteArrayGetGpuAddress optionalUserData
#define _np5_redXRteArrayGetGpuAddress rteParameters

#define _np1_redXRteCreateBottomLevelASGenerator outBottomLevelASGenerator
#define _np2_redXRteCreateBottomLevelASGenerator optionalFile
#define _np3_redXRteCreateBottomLevelASGenerator optionalLine
#define _np4_redXRteCreateBottomLevelASGenerator optionalUserData
#define _np5_redXRteCreateBottomLevelASGenerator rteParameters

#define _np1_redXRteCreateTopLevelASGenerator outTopLevelASGenerator
#define _np2_redXRteCreateTopLevelASGenerator optionalFile
#define _np3_redXRteCreateTopLevelASGenerator optionalLine
#define _np4_redXRteCreateTopLevelASGenerator optionalUserData
#define _np5_redXRteCreateTopLevelASGenerator rteParameters

#define _np1_redXRteCreateRootSignatureGenerator outRootSignatureGenerator
#define _np2_redXRteCreateRootSignatureGenerator optionalFile
#define _np3_redXRteCreateRootSignatureGenerator optionalLine
#define _np4_redXRteCreateRootSignatureGenerator optionalUserData
#define _np5_redXRteCreateRootSignatureGenerator rteParameters

#define _np1_redXRteCreateRayTracingPipelineGenerator device_ID3D12Device5
#define _np2_redXRteCreateRayTracingPipelineGenerator outRayTracingPipelineGenerator
#define _np3_redXRteCreateRayTracingPipelineGenerator optionalFile
#define _np4_redXRteCreateRayTracingPipelineGenerator optionalLine
#define _np5_redXRteCreateRayTracingPipelineGenerator optionalUserData
#define _np6_redXRteCreateRayTracingPipelineGenerator rteParameters

#define _np1_redXRteCreateShaderBindingTableGenerator outShaderBindingTableGenerator
#define _np2_redXRteCreateShaderBindingTableGenerator optionalFile
#define _np3_redXRteCreateShaderBindingTableGenerator optionalLine
#define _np4_redXRteCreateShaderBindingTableGenerator optionalUserData
#define _np5_redXRteCreateShaderBindingTableGenerator rteParameters

#define _np1_redXRteDestroyBottomLevelASGenerator bottomLevelASGenerator
#define _np2_redXRteDestroyBottomLevelASGenerator optionalFile
#define _np3_redXRteDestroyBottomLevelASGenerator optionalLine
#define _np4_redXRteDestroyBottomLevelASGenerator optionalUserData
#define _np5_redXRteDestroyBottomLevelASGenerator rteParameters

#define _np1_redXRteDestroyTopLevelASGenerator topLevelASGenerator
#define _np2_redXRteDestroyTopLevelASGenerator optionalFile
#define _np3_redXRteDestroyTopLevelASGenerator optionalLine
#define _np4_redXRteDestroyTopLevelASGenerator optionalUserData
#define _np5_redXRteDestroyTopLevelASGenerator rteParameters

#define _np1_redXRteDestroyRootSignatureGenerator rootSignatureGenerator
#define _np2_redXRteDestroyRootSignatureGenerator optionalFile
#define _np3_redXRteDestroyRootSignatureGenerator optionalLine
#define _np4_redXRteDestroyRootSignatureGenerator optionalUserData
#define _np5_redXRteDestroyRootSignatureGenerator rteParameters

#define _np1_redXRteDestroyRayTracingPipelineGenerator rayTracingPipelineGenerator
#define _np2_redXRteDestroyRayTracingPipelineGenerator optionalFile
#define _np3_redXRteDestroyRayTracingPipelineGenerator optionalLine
#define _np4_redXRteDestroyRayTracingPipelineGenerator optionalUserData
#define _np5_redXRteDestroyRayTracingPipelineGenerator rteParameters

#define _np1_redXRteDestroyShaderBindingTableGenerator shaderBindingTableGenerator
#define _np2_redXRteDestroyShaderBindingTableGenerator optionalFile
#define _np3_redXRteDestroyShaderBindingTableGenerator optionalLine
#define _np4_redXRteDestroyShaderBindingTableGenerator optionalUserData
#define _np5_redXRteDestroyShaderBindingTableGenerator rteParameters

#define _np1_redXRteBottomLevelASGeneratorAddVertexBuffer bottomLevelASGenerator
#define _np2_redXRteBottomLevelASGeneratorAddVertexBuffer vertexBuffer_ID3D12Resource
#define _np3_redXRteBottomLevelASGeneratorAddVertexBuffer vertexOffsetInBytes
#define _np4_redXRteBottomLevelASGeneratorAddVertexBuffer vertexCount
#define _np5_redXRteBottomLevelASGeneratorAddVertexBuffer vertexSizeInBytes
#define _np6_redXRteBottomLevelASGeneratorAddVertexBuffer transformBuffer_ID3D12Resource
#define _np7_redXRteBottomLevelASGeneratorAddVertexBuffer transformOffsetInBytes
#define _np8_redXRteBottomLevelASGeneratorAddVertexBuffer isOpaqueSuggestedDefaultValueIs1
#define _np9_redXRteBottomLevelASGeneratorAddVertexBuffer optionalFile
#define _np10_redXRteBottomLevelASGeneratorAddVertexBuffer optionalLine
#define _np11_redXRteBottomLevelASGeneratorAddVertexBuffer optionalUserData
#define _np12_redXRteBottomLevelASGeneratorAddVertexBuffer rteParameters

#define _np1_redXRteBottomLevelASGeneratorAddVertexIndexBuffer bottomLevelASGenerator
#define _np2_redXRteBottomLevelASGeneratorAddVertexIndexBuffer vertexBuffer_ID3D12Resource
#define _np3_redXRteBottomLevelASGeneratorAddVertexIndexBuffer vertexOffsetInBytes
#define _np4_redXRteBottomLevelASGeneratorAddVertexIndexBuffer vertexCount
#define _np5_redXRteBottomLevelASGeneratorAddVertexIndexBuffer vertexSizeInBytes
#define _np6_redXRteBottomLevelASGeneratorAddVertexIndexBuffer indexBuffer_ID3D12Resource
#define _np7_redXRteBottomLevelASGeneratorAddVertexIndexBuffer indexOffsetInBytes
#define _np8_redXRteBottomLevelASGeneratorAddVertexIndexBuffer indexCount
#define _np9_redXRteBottomLevelASGeneratorAddVertexIndexBuffer transformBuffer_ID3D12Resource
#define _np10_redXRteBottomLevelASGeneratorAddVertexIndexBuffer transformOffsetInBytes
#define _np11_redXRteBottomLevelASGeneratorAddVertexIndexBuffer isOpaqueSuggestedDefaultValueIs1
#define _np12_redXRteBottomLevelASGeneratorAddVertexIndexBuffer optionalFile
#define _np13_redXRteBottomLevelASGeneratorAddVertexIndexBuffer optionalLine
#define _np14_redXRteBottomLevelASGeneratorAddVertexIndexBuffer optionalUserData
#define _np15_redXRteBottomLevelASGeneratorAddVertexIndexBuffer rteParameters

#define _np1_redXRteBottomLevelASGeneratorComputeASBufferSizes bottomLevelASGenerator
#define _np2_redXRteBottomLevelASGeneratorComputeASBufferSizes device_ID3D12Device5
#define _np3_redXRteBottomLevelASGeneratorComputeASBufferSizes allowUpdate
#define _np4_redXRteBottomLevelASGeneratorComputeASBufferSizes scratchSizeInBytes
#define _np5_redXRteBottomLevelASGeneratorComputeASBufferSizes resultSizeInBytes
#define _np6_redXRteBottomLevelASGeneratorComputeASBufferSizes optionalFile
#define _np7_redXRteBottomLevelASGeneratorComputeASBufferSizes optionalLine
#define _np8_redXRteBottomLevelASGeneratorComputeASBufferSizes optionalUserData
#define _np9_redXRteBottomLevelASGeneratorComputeASBufferSizes rteParameters

#define _np1_redXRteBottomLevelASGeneratorGenerate bottomLevelASGenerator
#define _np2_redXRteBottomLevelASGeneratorGenerate commandList_ID3D12GraphicsCommandList4
#define _np3_redXRteBottomLevelASGeneratorGenerate scratchBuffer_ID3D12Resource
#define _np4_redXRteBottomLevelASGeneratorGenerate resultBuffer_ID3D12Resource
#define _np5_redXRteBottomLevelASGeneratorGenerate isUpdateOnlySuggestedDefaultValueIs0
#define _np6_redXRteBottomLevelASGeneratorGenerate previousResultSuggestedDefaultValueIsNull_ID3D12Resource
#define _np7_redXRteBottomLevelASGeneratorGenerate optionalFile
#define _np8_redXRteBottomLevelASGeneratorGenerate optionalLine
#define _np9_redXRteBottomLevelASGeneratorGenerate optionalUserData
#define _np10_redXRteBottomLevelASGeneratorGenerate rteParameters

#define _np1_redXRteTopLevelASGeneratorSetInstancesCount topLevelASGenerator
#define _np2_redXRteTopLevelASGeneratorSetInstancesCount instancesCount
#define _np3_redXRteTopLevelASGeneratorSetInstancesCount optionalFile
#define _np4_redXRteTopLevelASGeneratorSetInstancesCount optionalLine
#define _np5_redXRteTopLevelASGeneratorSetInstancesCount optionalUserData
#define _np6_redXRteTopLevelASGeneratorSetInstancesCount rteParameters

#define _np1_redXRteTopLevelASGeneratorComputeASBufferSizes topLevelASGenerator
#define _np2_redXRteTopLevelASGeneratorComputeASBufferSizes device_ID3D12Device5
#define _np3_redXRteTopLevelASGeneratorComputeASBufferSizes allowUpdate
#define _np4_redXRteTopLevelASGeneratorComputeASBufferSizes scratchSizeInBytes
#define _np5_redXRteTopLevelASGeneratorComputeASBufferSizes resultSizeInBytes
#define _np6_redXRteTopLevelASGeneratorComputeASBufferSizes descriptorsSizeInBytes
#define _np7_redXRteTopLevelASGeneratorComputeASBufferSizes optionalFile
#define _np8_redXRteTopLevelASGeneratorComputeASBufferSizes optionalLine
#define _np9_redXRteTopLevelASGeneratorComputeASBufferSizes optionalUserData
#define _np10_redXRteTopLevelASGeneratorComputeASBufferSizes rteParameters

#define _np1_redXRteTopLevelASGeneratorGenerate topLevelASGenerator
#define _np2_redXRteTopLevelASGeneratorGenerate commandList_ID3D12GraphicsCommandList4
#define _np3_redXRteTopLevelASGeneratorGenerate scratchBuffer_ID3D12Resource
#define _np4_redXRteTopLevelASGeneratorGenerate resultBuffer_ID3D12Resource
#define _np5_redXRteTopLevelASGeneratorGenerate descriptorsBuffer_ID3D12Resource
#define _np6_redXRteTopLevelASGeneratorGenerate isUpdateOnlySuggestedDefaultValueIs0
#define _np7_redXRteTopLevelASGeneratorGenerate previousResultSuggestedDefaultValueIsNull_ID3D12Resource
#define _np8_redXRteTopLevelASGeneratorGenerate optionalFile
#define _np9_redXRteTopLevelASGeneratorGenerate optionalLine
#define _np10_redXRteTopLevelASGeneratorGenerate optionalUserData
#define _np11_redXRteTopLevelASGeneratorGenerate rteParameters

#define _np1_redXRteRootSignatureGeneratorAddHeapRangesParameter rootSignatureGenerator
#define _np2_redXRteRootSignatureGeneratorAddHeapRangesParameter rangesCount
#define _np3_redXRteRootSignatureGeneratorAddHeapRangesParameter ranges_D3D12_DESCRIPTOR_RANGE
#define _np4_redXRteRootSignatureGeneratorAddHeapRangesParameter optionalFile
#define _np5_redXRteRootSignatureGeneratorAddHeapRangesParameter optionalLine
#define _np6_redXRteRootSignatureGeneratorAddHeapRangesParameter optionalUserData
#define _np7_redXRteRootSignatureGeneratorAddHeapRangesParameter rteParameters

#define _np1_redXRteRootSignatureGeneratorAddRootParameter rootSignatureGenerator
#define _np2_redXRteRootSignatureGeneratorAddRootParameter type_D3D12_ROOT_PARAMETER_TYPE
#define _np3_redXRteRootSignatureGeneratorAddRootParameter shaderRegisterSuggestedDefaultValueIs0
#define _np4_redXRteRootSignatureGeneratorAddRootParameter registerSpaceSuggestedDefaultValueIs0
#define _np5_redXRteRootSignatureGeneratorAddRootParameter numRootConstantsSuggestedDefaultValueIs1
#define _np6_redXRteRootSignatureGeneratorAddRootParameter optionalFile
#define _np7_redXRteRootSignatureGeneratorAddRootParameter optionalLine
#define _np8_redXRteRootSignatureGeneratorAddRootParameter optionalUserData
#define _np9_redXRteRootSignatureGeneratorAddRootParameter rteParameters

#define _np1_redXRteRootSignatureGeneratorGenerate rootSignatureGenerator
#define _np2_redXRteRootSignatureGeneratorGenerate device_ID3D12Device
#define _np3_redXRteRootSignatureGeneratorGenerate isLocal
#define _np4_redXRteRootSignatureGeneratorGenerate outRootSignature_ID3D12RootSignature
#define _np5_redXRteRootSignatureGeneratorGenerate optionalFile
#define _np6_redXRteRootSignatureGeneratorGenerate optionalLine
#define _np7_redXRteRootSignatureGeneratorGenerate optionalUserData
#define _np8_redXRteRootSignatureGeneratorGenerate rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorAddLibrary rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorAddLibrary dxilLibraryBufferSize
#define _np3_redXRteRayTracingPipelineGeneratorAddLibrary dxilLibraryBufferPointer
#define _np4_redXRteRayTracingPipelineGeneratorAddLibrary symbolExportsCount
#define _np5_redXRteRayTracingPipelineGeneratorAddLibrary symbolExports
#define _np6_redXRteRayTracingPipelineGeneratorAddLibrary optionalFile
#define _np7_redXRteRayTracingPipelineGeneratorAddLibrary optionalLine
#define _np8_redXRteRayTracingPipelineGeneratorAddLibrary optionalUserData
#define _np9_redXRteRayTracingPipelineGeneratorAddLibrary rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorAddHitGroup rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorAddHitGroup hitGroupName
#define _np3_redXRteRayTracingPipelineGeneratorAddHitGroup closestHitSymbol
#define _np4_redXRteRayTracingPipelineGeneratorAddHitGroup anyHitSymbolSuggestedDefaultValueIsNull
#define _np5_redXRteRayTracingPipelineGeneratorAddHitGroup intersectionSymbolSuggestedDefaultValueIsNull
#define _np6_redXRteRayTracingPipelineGeneratorAddHitGroup optionalFile
#define _np7_redXRteRayTracingPipelineGeneratorAddHitGroup optionalLine
#define _np8_redXRteRayTracingPipelineGeneratorAddHitGroup optionalUserData
#define _np9_redXRteRayTracingPipelineGeneratorAddHitGroup rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation rootSignature_ID3D12RootSignature
#define _np3_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation symbolsCount
#define _np4_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation symbols
#define _np5_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation optionalFile
#define _np6_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation optionalLine
#define _np7_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation optionalUserData
#define _np8_redXRteRayTracingPipelineGeneratorAddRootSignatureAssociation rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorSetMaxPayloadSize rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorSetMaxPayloadSize sizeInBytes
#define _np3_redXRteRayTracingPipelineGeneratorSetMaxPayloadSize optionalFile
#define _np4_redXRteRayTracingPipelineGeneratorSetMaxPayloadSize optionalLine
#define _np5_redXRteRayTracingPipelineGeneratorSetMaxPayloadSize optionalUserData
#define _np6_redXRteRayTracingPipelineGeneratorSetMaxPayloadSize rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorSetMaxAttributeSize rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorSetMaxAttributeSize sizeInBytes
#define _np3_redXRteRayTracingPipelineGeneratorSetMaxAttributeSize optionalFile
#define _np4_redXRteRayTracingPipelineGeneratorSetMaxAttributeSize optionalLine
#define _np5_redXRteRayTracingPipelineGeneratorSetMaxAttributeSize optionalUserData
#define _np6_redXRteRayTracingPipelineGeneratorSetMaxAttributeSize rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorSetMaxRecursionDepth rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorSetMaxRecursionDepth maxDepth
#define _np3_redXRteRayTracingPipelineGeneratorSetMaxRecursionDepth optionalFile
#define _np4_redXRteRayTracingPipelineGeneratorSetMaxRecursionDepth optionalLine
#define _np5_redXRteRayTracingPipelineGeneratorSetMaxRecursionDepth optionalUserData
#define _np6_redXRteRayTracingPipelineGeneratorSetMaxRecursionDepth rteParameters

#define _np1_redXRteRayTracingPipelineGeneratorGenerate rayTracingPipelineGenerator
#define _np2_redXRteRayTracingPipelineGeneratorGenerate outStateObject_ID3D12StateObject
#define _np3_redXRteRayTracingPipelineGeneratorGenerate outStateObjectProperties_ID3D12StateObjectProperties
#define _np4_redXRteRayTracingPipelineGeneratorGenerate optionalFile
#define _np5_redXRteRayTracingPipelineGeneratorGenerate optionalLine
#define _np6_redXRteRayTracingPipelineGeneratorGenerate optionalUserData
#define _np7_redXRteRayTracingPipelineGeneratorGenerate rteParameters

#define _np1_redXRteShaderBindingTableGeneratorAddRayGenerationProgram shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorAddRayGenerationProgram entryPoint
#define _np3_redXRteShaderBindingTableGeneratorAddRayGenerationProgram inputDatasCount
#define _np4_redXRteShaderBindingTableGeneratorAddRayGenerationProgram inputDatas
#define _np5_redXRteShaderBindingTableGeneratorAddRayGenerationProgram optionalFile
#define _np6_redXRteShaderBindingTableGeneratorAddRayGenerationProgram optionalLine
#define _np7_redXRteShaderBindingTableGeneratorAddRayGenerationProgram optionalUserData
#define _np8_redXRteShaderBindingTableGeneratorAddRayGenerationProgram rteParameters

#define _np1_redXRteShaderBindingTableGeneratorAddMissProgram shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorAddMissProgram entryPoint
#define _np3_redXRteShaderBindingTableGeneratorAddMissProgram inputDatasCount
#define _np4_redXRteShaderBindingTableGeneratorAddMissProgram inputDatas
#define _np5_redXRteShaderBindingTableGeneratorAddMissProgram optionalFile
#define _np6_redXRteShaderBindingTableGeneratorAddMissProgram optionalLine
#define _np7_redXRteShaderBindingTableGeneratorAddMissProgram optionalUserData
#define _np8_redXRteShaderBindingTableGeneratorAddMissProgram rteParameters

#define _np1_redXRteShaderBindingTableGeneratorAddHitGroup shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorAddHitGroup entryPoint
#define _np3_redXRteShaderBindingTableGeneratorAddHitGroup inputDatasCount
#define _np4_redXRteShaderBindingTableGeneratorAddHitGroup inputDatas
#define _np5_redXRteShaderBindingTableGeneratorAddHitGroup optionalFile
#define _np6_redXRteShaderBindingTableGeneratorAddHitGroup optionalLine
#define _np7_redXRteShaderBindingTableGeneratorAddHitGroup optionalUserData
#define _np8_redXRteShaderBindingTableGeneratorAddHitGroup rteParameters

#define _np1_redXRteShaderBindingTableGeneratorComputeSBTSize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorComputeSBTSize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorComputeSBTSize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorComputeSBTSize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorComputeSBTSize rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGenerate shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGenerate sbtBuffer_ID3D12Resource
#define _np3_redXRteShaderBindingTableGeneratorGenerate raytracingPipeline_ID3D12StateObjectProperties
#define _np4_redXRteShaderBindingTableGeneratorGenerate optionalFile
#define _np5_redXRteShaderBindingTableGeneratorGenerate optionalLine
#define _np6_redXRteShaderBindingTableGeneratorGenerate optionalUserData
#define _np7_redXRteShaderBindingTableGeneratorGenerate rteParameters

#define _np1_redXRteShaderBindingTableGeneratorReset shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorReset optionalFile
#define _np3_redXRteShaderBindingTableGeneratorReset optionalLine
#define _np4_redXRteShaderBindingTableGeneratorReset optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorReset rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGetRayGenSectionSize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGetRayGenSectionSize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorGetRayGenSectionSize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorGetRayGenSectionSize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorGetRayGenSectionSize rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGetRayGenEntrySize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGetRayGenEntrySize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorGetRayGenEntrySize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorGetRayGenEntrySize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorGetRayGenEntrySize rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGetMissSectionSize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGetMissSectionSize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorGetMissSectionSize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorGetMissSectionSize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorGetMissSectionSize rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGetMissEntrySize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGetMissEntrySize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorGetMissEntrySize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorGetMissEntrySize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorGetMissEntrySize rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGetHitGroupSectionSize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGetHitGroupSectionSize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorGetHitGroupSectionSize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorGetHitGroupSectionSize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorGetHitGroupSectionSize rteParameters

#define _np1_redXRteShaderBindingTableGeneratorGetHitGroupEntrySize shaderBindingTableGenerator
#define _np2_redXRteShaderBindingTableGeneratorGetHitGroupEntrySize optionalFile
#define _np3_redXRteShaderBindingTableGeneratorGetHitGroupEntrySize optionalLine
#define _np4_redXRteShaderBindingTableGeneratorGetHitGroupEntrySize optionalUserData
#define _np5_redXRteShaderBindingTableGeneratorGetHitGroupEntrySize rteParameters

#define _np1_redXRteCallSetStateObject calls
#define _np2_redXRteCallSetStateObject stateObject_ID3D12StateObject
#define _np3_redXRteCallSetStateObject optionalFile
#define _np4_redXRteCallSetStateObject optionalLine
#define _np5_redXRteCallSetStateObject optionalUserData
#define _np6_redXRteCallSetStateObject rteParameters

#define _np1_redXRteCallDispatchRays calls
#define _np2_redXRteCallDispatchRays dispatchRaysDescription_D3D12_DISPATCH_RAYS_DESC
#define _np3_redXRteCallDispatchRays optionalFile
#define _np4_redXRteCallDispatchRays optionalLine
#define _np5_redXRteCallDispatchRays optionalUserData
#define _np6_redXRteCallDispatchRays rteParameters

