#pragma once

#define _np1_red2CreateContext malloc
#define _np2_red2CreateContext free
#define _np3_red2CreateContext optionalMallocTagged
#define _np4_red2CreateContext optionalFreeTagged
#define _np5_red2CreateContext debugCallback
#define _np6_red2CreateContext sdkVersion
#define _np7_red2CreateContext sdkExtensionsCount
#define _np8_red2CreateContext sdkExtensions
#define _np9_red2CreateContext optionalProgramName
#define _np10_red2CreateContext optionalProgramVersion
#define _np11_red2CreateContext optionalEngineName
#define _np12_red2CreateContext optionalEngineVersion
#define _np13_red2CreateContext optionalSettings
#define _np14_red2CreateContext outContext2
#define _np15_red2CreateContext outStatuses
#define _np16_red2CreateContext optionalFile
#define _np17_red2CreateContext optionalLine
#define _np18_red2CreateContext optionalUserData

#define _np1_red2CreateImage context
#define _np2_red2CreateImage gpu
#define _np3_red2CreateImage handleName
#define _np4_red2CreateImage dimensions
#define _np5_red2CreateImage format
#define _np6_red2CreateImage xformat
#define _np7_red2CreateImage width
#define _np8_red2CreateImage height
#define _np9_red2CreateImage depth
#define _np10_red2CreateImage levelsCount
#define _np11_red2CreateImage layersCount
#define _np12_red2CreateImage multisampleCount
#define _np13_red2CreateImage restrictToAccess
#define _np14_red2CreateImage initialAccess
#define _np15_red2CreateImage initialQueueFamilyIndex
#define _np16_red2CreateImage dedicate
#define _np17_red2CreateImage outImage
#define _np18_red2CreateImage outStatuses
#define _np19_red2CreateImage optionalFile
#define _np20_red2CreateImage optionalLine
#define _np21_red2CreateImage optionalUserData

#define _np1_red2CreateTexture context
#define _np2_red2CreateTexture gpu
#define _np3_red2CreateTexture handleName
#define _np4_red2CreateTexture image
#define _np5_red2CreateTexture parts
#define _np6_red2CreateTexture dimensions
#define _np7_red2CreateTexture format
#define _np8_red2CreateTexture xformat
#define _np9_red2CreateTexture levelsFirst
#define _np10_red2CreateTexture levelsCount
#define _np11_red2CreateTexture layersFirst
#define _np12_red2CreateTexture layersCount
#define _np13_red2CreateTexture restrictToAccess
#define _np14_red2CreateTexture outTexture
#define _np15_red2CreateTexture outStatuses
#define _np16_red2CreateTexture optionalFile
#define _np17_red2CreateTexture optionalLine
#define _np18_red2CreateTexture optionalUserData

#define _np1_red2CreateStructDeclaration context
#define _np2_red2CreateStructDeclaration gpu
#define _np3_red2CreateStructDeclaration handleName
#define _np4_red2CreateStructDeclaration structDeclarationMembersCount
#define _np5_red2CreateStructDeclaration structDeclarationMembers
#define _np6_red2CreateStructDeclaration structDeclarationMembersArrayROCount
#define _np7_red2CreateStructDeclaration structDeclarationMembersArrayRO
#define _np8_red2CreateStructDeclaration procedureParametersHandlesDeclaration
#define _np9_red2CreateStructDeclaration outStructDeclaration
#define _np10_red2CreateStructDeclaration outStatuses
#define _np11_red2CreateStructDeclaration optionalFile
#define _np12_red2CreateStructDeclaration optionalLine
#define _np13_red2CreateStructDeclaration optionalUserData

#define _np1_red2CreateProcedureParameters context
#define _np2_red2CreateProcedureParameters gpu
#define _np3_red2CreateProcedureParameters handleName
#define _np4_red2CreateProcedureParameters procedureParametersDeclaration
#define _np5_red2CreateProcedureParameters outProcedureParameters
#define _np6_red2CreateProcedureParameters outStatuses
#define _np7_red2CreateProcedureParameters optionalFile
#define _np8_red2CreateProcedureParameters optionalLine
#define _np9_red2CreateProcedureParameters optionalUserData

#define _np1_red2CreateProcedure context
#define _np2_red2CreateProcedure gpu
#define _np3_red2CreateProcedure handleName
#define _np4_red2CreateProcedure procedureCache
#define _np5_red2CreateProcedure procedureDependencyOnRenderTargets
#define _np6_red2CreateProcedure procedureParameters
#define _np7_red2CreateProcedure gpuCodeVertexMainProcedureName
#define _np8_red2CreateProcedure gpuCodeVertex
#define _np9_red2CreateProcedure gpuCodeFragmentMainProcedureName
#define _np10_red2CreateProcedure gpuCodeFragment
#define _np11_red2CreateProcedure state
#define _np12_red2CreateProcedure stateExtension
#define _np13_red2CreateProcedure deriveBase
#define _np14_red2CreateProcedure deriveFrom
#define _np15_red2CreateProcedure outProcedure
#define _np16_red2CreateProcedure outStatuses
#define _np17_red2CreateProcedure optionalFile
#define _np18_red2CreateProcedure optionalLine
#define _np19_red2CreateProcedure optionalUserData

#define _np1_red2CreateCalls context
#define _np2_red2CreateCalls gpu
#define _np3_red2CreateCalls handleName
#define _np4_red2CreateCalls queueFamilyIndex
#define _np5_red2CreateCalls outCalls
#define _np6_red2CreateCalls outStatuses
#define _np7_red2CreateCalls optionalFile
#define _np8_red2CreateCalls optionalLine
#define _np9_red2CreateCalls optionalUserData

#define _np1_red2CreateCallsReusable context
#define _np2_red2CreateCallsReusable gpu
#define _np3_red2CreateCallsReusable handleName
#define _np4_red2CreateCallsReusable queueFamilyIndex
#define _np5_red2CreateCallsReusable outCalls
#define _np6_red2CreateCallsReusable outStatuses
#define _np7_red2CreateCallsReusable optionalFile
#define _np8_red2CreateCallsReusable optionalLine
#define _np9_red2CreateCallsReusable optionalUserData

#define _np1_red2DestroyContext context2
#define _np2_red2DestroyContext optionalFile
#define _np3_red2DestroyContext optionalLine
#define _np4_red2DestroyContext optionalUserData

#define _np1_red2DestroyStructDeclaration context
#define _np2_red2DestroyStructDeclaration gpu
#define _np3_red2DestroyStructDeclaration structDeclaration
#define _np4_red2DestroyStructDeclaration optionalFile
#define _np5_red2DestroyStructDeclaration optionalLine
#define _np6_red2DestroyStructDeclaration optionalUserData

#define _np1_red2DestroyProcedureParameters context
#define _np2_red2DestroyProcedureParameters gpu
#define _np3_red2DestroyProcedureParameters procedureParameters
#define _np4_red2DestroyProcedureParameters optionalFile
#define _np5_red2DestroyProcedureParameters optionalLine
#define _np6_red2DestroyProcedureParameters optionalUserData

#define _np1_red2DestroyCalls context
#define _np2_red2DestroyCalls gpu
#define _np3_red2DestroyCalls calls
#define _np4_red2DestroyCalls optionalFile
#define _np5_red2DestroyCalls optionalLine
#define _np6_red2DestroyCalls optionalUserData

#define _np1_red2CallsSet calls
#define _np2_red2CallsSet outStatuses
#define _np3_red2CallsSet optionalFile
#define _np4_red2CallsSet optionalLine
#define _np5_red2CallsSet optionalUserData

#define _np1_red2CallsEnd calls
#define _np2_red2CallsEnd outStatuses
#define _np3_red2CallsEnd optionalFile
#define _np4_red2CallsEnd optionalLine
#define _np5_red2CallsEnd optionalUserData

#define _np1_red2CallsAppendHandleToDestroy calls
#define _np2_red2CallsAppendHandleToDestroy handleToDestroyWhenCallsAreReset
#define _np3_red2CallsAppendHandleToDestroy handleToDestroyWhenCallsAreResetType

#define _np1_red2CallsFreeAllInlineStructsMemorys calls
#define _np2_red2CallsFreeAllInlineStructsMemorys optionalFile
#define _np3_red2CallsFreeAllInlineStructsMemorys optionalLine
#define _np4_red2CallsFreeAllInlineStructsMemorys optionalUserData

#define _np1_red2PresentGetImageIndex context2
#define _np2_red2PresentGetImageIndex gpu
#define _np3_red2PresentGetImageIndex present
#define _np4_red2PresentGetImageIndex signalCpuSignal
#define _np5_red2PresentGetImageIndex signalGpuSignal
#define _np6_red2PresentGetImageIndex outImageIndex
#define _np7_red2PresentGetImageIndex outStatuses
#define _np8_red2PresentGetImageIndex optionalFile
#define _np9_red2PresentGetImageIndex optionalLine
#define _np10_red2PresentGetImageIndex optionalUserData

#define _np1_red2GetWsiStoredGpuSignal context2
#define _np2_red2GetWsiStoredGpuSignal gpu
#define _np3_red2GetWsiStoredGpuSignal present
#define _np4_red2GetWsiStoredGpuSignal presentImageIndex
#define _np5_red2GetWsiStoredGpuSignal outGpuSignal
#define _np6_red2GetWsiStoredGpuSignal outStatuses
#define _np7_red2GetWsiStoredGpuSignal optionalFile
#define _np8_red2GetWsiStoredGpuSignal optionalLine
#define _np9_red2GetWsiStoredGpuSignal optionalUserData

#define _np1_red2QueueSubmit context2
#define _np2_red2QueueSubmit gpu
#define _np3_red2QueueSubmit queue
#define _np4_red2QueueSubmit timelinesCount
#define _np5_red2QueueSubmit timelines
#define _np6_red2QueueSubmit outQueueSubmissionTicketArrayIndex
#define _np7_red2QueueSubmit outQueueSubmissionTicket
#define _np8_red2QueueSubmit outStatuses
#define _np9_red2QueueSubmit optionalFile
#define _np10_red2QueueSubmit optionalLine
#define _np11_red2QueueSubmit optionalUserData

#define _np1_red2QueueSubmitTrackableSimple context2
#define _np2_red2QueueSubmitTrackableSimple gpu
#define _np3_red2QueueSubmitTrackableSimple queue
#define _np4_red2QueueSubmitTrackableSimple callsCount
#define _np5_red2QueueSubmitTrackableSimple calls
#define _np6_red2QueueSubmitTrackableSimple outStatuses
#define _np7_red2QueueSubmitTrackableSimple optionalFile
#define _np8_red2QueueSubmitTrackableSimple optionalLine
#define _np9_red2QueueSubmitTrackableSimple optionalUserData

#define _np1_red2RedXOnlyCreateQueue context
#define _np2_red2RedXOnlyCreateQueue gpu
#define _np3_red2RedXOnlyCreateQueue handleName
#define _np4_red2RedXOnlyCreateQueue canCopy
#define _np5_red2RedXOnlyCreateQueue canDraw
#define _np6_red2RedXOnlyCreateQueue canCompute
#define _np7_red2RedXOnlyCreateQueue priority
#define _np8_red2RedXOnlyCreateQueue disableGpuTimeout
#define _np9_red2RedXOnlyCreateQueue outStatuses
#define _np10_red2RedXOnlyCreateQueue optionalFile
#define _np11_red2RedXOnlyCreateQueue optionalLine
#define _np12_red2RedXOnlyCreateQueue optionalUserData

#define _np1_red2QueueWaitIdle context
#define _np2_red2QueueWaitIdle gpu
#define _np3_red2QueueWaitIdle presentQueue
#define _np4_red2QueueWaitIdle optionalFile
#define _np5_red2QueueWaitIdle optionalLine
#define _np6_red2QueueWaitIdle optionalUserData

#define _np1_red2GpuWaitIdle context
#define _np2_red2GpuWaitIdle gpuInfo
#define _np3_red2GpuWaitIdle optionalFile
#define _np4_red2GpuWaitIdle optionalLine
#define _np5_red2GpuWaitIdle optionalUserData

#define _np1_red2PickResourceMemoryTypeIndex gpuInfo
#define _np2_red2PickResourceMemoryTypeIndex requireMappableMemoryCoherency
#define _np3_red2PickResourceMemoryTypeIndex resourceDesiredMemoryType
#define _np4_red2PickResourceMemoryTypeIndex resourceMemoryTypesSupported

#define _np1_red2IsQueueSubmissionFinished context2
#define _np2_red2IsQueueSubmissionFinished gpu
#define _np3_red2IsQueueSubmissionFinished queueSubmissionTicketArrayIndex
#define _np4_red2IsQueueSubmissionFinished queueSubmissionTicket
#define _np5_red2IsQueueSubmissionFinished optionalFile
#define _np6_red2IsQueueSubmissionFinished optionalLine
#define _np7_red2IsQueueSubmissionFinished optionalUserData

#define _np1_red2IsQueueSubmissionFinishedByTicketAlone context2
#define _np2_red2IsQueueSubmissionFinishedByTicketAlone gpu
#define _np3_red2IsQueueSubmissionFinishedByTicketAlone queueSubmissionTicket
#define _np4_red2IsQueueSubmissionFinishedByTicketAlone optionalFile
#define _np5_red2IsQueueSubmissionFinishedByTicketAlone optionalLine
#define _np6_red2IsQueueSubmissionFinishedByTicketAlone optionalUserData

#define _np1_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket context2
#define _np2_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket gpu
#define _np3_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket queueSubmissionTicket
#define _np4_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket outStatuses
#define _np5_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket optionalFile
#define _np6_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket optionalLine
#define _np7_red2AreAllQueueSubmissionsFinishedUpToAndIncludingTicket optionalUserData

#define _np1_red2WaitForQueueSubmissionToFinish context2
#define _np2_red2WaitForQueueSubmissionToFinish gpu
#define _np3_red2WaitForQueueSubmissionToFinish queueSubmissionTicketArrayIndex
#define _np4_red2WaitForQueueSubmissionToFinish queueSubmissionTicket
#define _np5_red2WaitForQueueSubmissionToFinish outStatuses
#define _np6_red2WaitForQueueSubmissionToFinish optionalFile
#define _np7_red2WaitForQueueSubmissionToFinish optionalLine
#define _np8_red2WaitForQueueSubmissionToFinish optionalUserData

#define _np1_red2WaitForQueueSubmissionToFinishByTicketAlone context2
#define _np2_red2WaitForQueueSubmissionToFinishByTicketAlone gpu
#define _np3_red2WaitForQueueSubmissionToFinishByTicketAlone queueSubmissionTicket
#define _np4_red2WaitForQueueSubmissionToFinishByTicketAlone outStatuses
#define _np5_red2WaitForQueueSubmissionToFinishByTicketAlone optionalFile
#define _np6_red2WaitForQueueSubmissionToFinishByTicketAlone optionalLine
#define _np7_red2WaitForQueueSubmissionToFinishByTicketAlone optionalUserData

#define _np1_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket context2
#define _np2_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket gpu
#define _np3_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket queueSubmissionTicket
#define _np4_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket outStatuses
#define _np5_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket optionalFile
#define _np6_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket optionalLine
#define _np7_red2WaitForAllQueueSubmissionsToFinishUpToAndIncludingTicket optionalUserData

#define _np1_red2WaitForAllQueueSubmissionsToFinish context2
#define _np2_red2WaitForAllQueueSubmissionsToFinish gpu
#define _np3_red2WaitForAllQueueSubmissionsToFinish outStatuses
#define _np4_red2WaitForAllQueueSubmissionsToFinish optionalFile
#define _np5_red2WaitForAllQueueSubmissionsToFinish optionalLine
#define _np6_red2WaitForAllQueueSubmissionsToFinish optionalUserData

#define _np1_red2StructDeclarationGetRedHandle structDeclaration

#define _np1_red2StructDeclarationGetMembersPointer structDeclaration

#define _np1_red2StructDeclarationGetMembersCounts structDeclaration
#define _np2_red2StructDeclarationGetMembersCounts outStructDeclarationMembersCount
#define _np3_red2StructDeclarationGetMembersCounts outMembersOfTypeArrayROConstantCount
#define _np4_red2StructDeclarationGetMembersCounts outMembersOfTypeArrayROOrArrayRWCount
#define _np5_red2StructDeclarationGetMembersCounts outMembersOfTypeTextureROCount
#define _np6_red2StructDeclarationGetMembersCounts outMembersOfTypeTextureRWCount
#define _np7_red2StructDeclarationGetMembersCounts outMembersOfTypeInlineSamplerCount
#define _np8_red2StructDeclarationGetMembersCounts outMembersOfTypeSamplerCount

#define _np1_red2ProcedureParametersGetRedHandle procedureParameters

#define _np1_red2ProcedureParametersGetStructDeclaration procedureParameters
#define _np2_red2ProcedureParametersGetStructDeclaration structIndex

#define _np1_red2CallsGetRedHandles calls
#define _np2_red2CallsGetRedHandles outContext
#define _np3_red2CallsGetRedHandles outGpu
#define _np4_red2CallsGetRedHandles outCalls

#define _np1_red2CallsGetHandlesToDestroy calls
#define _np2_red2CallsGetHandlesToDestroy outHandlesToDestroyWhenCallsAreResetCount

#define _np1_red2CallsGetHandlesToDestroyType calls
#define _np2_red2CallsGetHandlesToDestroyType outHandlesToDestroyWhenCallsAreResetTypeCount

#define _np1_red2CallsSetHandlesToDestroyCustomCallback calls
#define _np2_red2CallsSetHandlesToDestroyCustomCallback optionalCustomHandleAndHandleTypeDestroyWhenCallsAreResetCallback

#define _np1_red2CallsGetQueueSubmitTrackableTicket calls
#define _np2_red2CallsGetQueueSubmitTrackableTicket outQueueSubmissionTicketArrayIndex
#define _np3_red2CallsGetQueueSubmitTrackableTicket outQueueSubmissionTicket

#define _np1_red2CallsSetQueueSubmitTrackableTicket calls
#define _np2_red2CallsSetQueueSubmitTrackableTicket queueSubmissionTicketArrayIndex
#define _np3_red2CallsSetQueueSubmitTrackableTicket queueSubmissionTicket

#define _np1_red2CallResolveDepthStencilTexture addresses
#define _np2_red2CallResolveDepthStencilTexture calls
#define _np3_red2CallResolveDepthStencilTexture width
#define _np4_red2CallResolveDepthStencilTexture height
#define _np5_red2CallResolveDepthStencilTexture sourceDepthStencilTexture
#define _np6_red2CallResolveDepthStencilTexture sourceDepthStencilTextureFormatRedOnly
#define _np7_red2CallResolveDepthStencilTexture sourceDepthStencilTextureMultisampleCount
#define _np8_red2CallResolveDepthStencilTexture targetDepthStencilTexture
#define _np9_red2CallResolveDepthStencilTexture targetDepthStencilTextureFormatRedXOnly
#define _np10_red2CallResolveDepthStencilTexture depthResolveModeRedOnly
#define _np11_red2CallResolveDepthStencilTexture stencilResolveModeRedOnly
#define _np12_red2CallResolveDepthStencilTexture outStatuses
#define _np13_red2CallResolveDepthStencilTexture optionalFile
#define _np14_red2CallResolveDepthStencilTexture optionalLine
#define _np15_red2CallResolveDepthStencilTexture optionalUserData

#define _np1_red2CallResolveColorTexture addresses
#define _np2_red2CallResolveColorTexture calls
#define _np3_red2CallResolveColorTexture width
#define _np4_red2CallResolveColorTexture height
#define _np5_red2CallResolveColorTexture sourceColorTexture
#define _np6_red2CallResolveColorTexture sourceColorTextureFormatRedOnly
#define _np7_red2CallResolveColorTexture sourceColorTextureMultisampleCount
#define _np8_red2CallResolveColorTexture targetColorTexture
#define _np9_red2CallResolveColorTexture targetColorTextureFormatRedXOnly
#define _np10_red2CallResolveColorTexture outStatuses
#define _np11_red2CallResolveColorTexture optionalFile
#define _np12_red2CallResolveColorTexture optionalLine
#define _np13_red2CallResolveColorTexture optionalUserData

#define _np1_red2CallClearDepthStencilTexture addresses
#define _np2_red2CallClearDepthStencilTexture calls
#define _np3_red2CallClearDepthStencilTexture width
#define _np4_red2CallClearDepthStencilTexture height
#define _np5_red2CallClearDepthStencilTexture depthStencilTexture
#define _np6_red2CallClearDepthStencilTexture depthStencilTextureFormatRedOnly
#define _np7_red2CallClearDepthStencilTexture depthStencilTextureMultisampleCount
#define _np8_red2CallClearDepthStencilTexture clearDepth
#define _np9_red2CallClearDepthStencilTexture depthClearValue
#define _np10_red2CallClearDepthStencilTexture clearStencil
#define _np11_red2CallClearDepthStencilTexture stencilClearValue
#define _np12_red2CallClearDepthStencilTexture outStatuses
#define _np13_red2CallClearDepthStencilTexture optionalFile
#define _np14_red2CallClearDepthStencilTexture optionalLine
#define _np15_red2CallClearDepthStencilTexture optionalUserData

#define _np1_red2CallClearColorTexture addresses
#define _np2_red2CallClearColorTexture calls
#define _np3_red2CallClearColorTexture width
#define _np4_red2CallClearColorTexture height
#define _np5_red2CallClearColorTexture colorTexture
#define _np6_red2CallClearColorTexture colorTextureFormatRedOnly
#define _np7_red2CallClearColorTexture colorTextureMultisampleCount
#define _np8_red2CallClearColorTexture colorClearValueR
#define _np9_red2CallClearColorTexture colorClearValueG
#define _np10_red2CallClearColorTexture colorClearValueB
#define _np11_red2CallClearColorTexture colorClearValueA
#define _np12_red2CallClearColorTexture outStatuses
#define _np13_red2CallClearColorTexture optionalFile
#define _np14_red2CallClearColorTexture optionalLine
#define _np15_red2CallClearColorTexture optionalUserData

#define _np1_red2RedXOnlyCallDiscardResource addresses
#define _np2_red2RedXOnlyCallDiscardResource calls
#define _np3_red2RedXOnlyCallDiscardResource handleResource
#define _np4_red2RedXOnlyCallDiscardResource optionalDiscardRegion

#define _np1_red2CallSetRenderTargets addresses
#define _np2_red2CallSetRenderTargets calls
#define _np3_red2CallSetRenderTargets width
#define _np4_red2CallSetRenderTargets height
#define _np5_red2CallSetRenderTargets depthStencilTexture
#define _np6_red2CallSetRenderTargets depthStencilTextureFormatRedOnly
#define _np7_red2CallSetRenderTargets depthStencilTextureMultisampleCount
#define _np8_red2CallSetRenderTargets colorsTextureCountMax8
#define _np9_red2CallSetRenderTargets colorsTexture
#define _np10_red2CallSetRenderTargets colorsTextureFormatRedOnly
#define _np11_red2CallSetRenderTargets colorsTextureMultisampleCount
#define _np12_red2CallSetRenderTargets optionalDiscardRedOnly
#define _np13_red2CallSetRenderTargets outStatuses
#define _np14_red2CallSetRenderTargets optionalFile
#define _np15_red2CallSetRenderTargets optionalLine
#define _np16_red2CallSetRenderTargets optionalUserData

#define _np1_red2CallEndRenderTargets addresses
#define _np2_red2CallEndRenderTargets calls

#define _np1_red2CallAllocateAndSetInlineStructsMemory addresses
#define _np2_red2CallAllocateAndSetInlineStructsMemory calls
#define _np3_red2CallAllocateAndSetInlineStructsMemory structsMemoryHandleName
#define _np4_red2CallAllocateAndSetInlineStructsMemory maxStructsCount
#define _np5_red2CallAllocateAndSetInlineStructsMemory maxStructsOfTypeSamplerCount
#define _np6_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeArrayROConstantCount
#define _np7_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeArrayROOrArrayRWCount
#define _np8_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeTextureROCount
#define _np9_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeTextureRWCount
#define _np10_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeInlineSamplerCount
#define _np11_red2CallAllocateAndSetInlineStructsMemory maxStructsMembersOfTypeSamplerCount
#define _np12_red2CallAllocateAndSetInlineStructsMemory outStatuses
#define _np13_red2CallAllocateAndSetInlineStructsMemory optionalFile
#define _np14_red2CallAllocateAndSetInlineStructsMemory optionalLine
#define _np15_red2CallAllocateAndSetInlineStructsMemory optionalUserData

#define _np1_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters addresses
#define _np2_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters calls
#define _np3_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters structsMemoryHandleName
#define _np4_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters procedureParametersCount
#define _np5_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters procedureParameters
#define _np6_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters outStatuses
#define _np7_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters optionalFile
#define _np8_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters optionalLine
#define _np9_red2CallAllocateAndSetInlineStructsMemoryFromProcedureParameters optionalUserData

#define _np1_red2CallSuballocateAndSetProcedureParametersInlineStruct addresses
#define _np2_red2CallSuballocateAndSetProcedureParametersInlineStruct calls
#define _np3_red2CallSuballocateAndSetProcedureParametersInlineStruct procedureType
#define _np4_red2CallSuballocateAndSetProcedureParametersInlineStruct procedureParameters
#define _np5_red2CallSuballocateAndSetProcedureParametersInlineStruct structIndex
#define _np6_red2CallSuballocateAndSetProcedureParametersInlineStruct structAllRedHandlesInParameterArrayOrderOfRed2CreateStructDeclarationStructDeclarationMembers
#define _np7_red2CallSuballocateAndSetProcedureParametersInlineStruct outStatuses
#define _np8_red2CallSuballocateAndSetProcedureParametersInlineStruct optionalFile
#define _np9_red2CallSuballocateAndSetProcedureParametersInlineStruct optionalLine
#define _np10_red2CallSuballocateAndSetProcedureParametersInlineStruct optionalUserData

#define _np1_red2CallGpuToCpuSignalSignal addresses
#define _np2_red2CallGpuToCpuSignalSignal calls
#define _np3_red2CallGpuToCpuSignalSignal signalGpuToCpuSignal
#define _np4_red2CallGpuToCpuSignalSignal setTo8192

#define _np1_red2CallCopyArrayToArray addresses
#define _np2_red2CallCopyArrayToArray calls
#define _np3_red2CallCopyArrayToArray arrayR
#define _np4_red2CallCopyArrayToArray arrayW
#define _np5_red2CallCopyArrayToArray rangesCount
#define _np6_red2CallCopyArrayToArray ranges

#define _np1_red2CallProcedure addresses
#define _np2_red2CallProcedure calls
#define _np3_red2CallProcedure vertexCount
#define _np4_red2CallProcedure instanceCount
#define _np5_red2CallProcedure vertexFirst
#define _np6_red2CallProcedure instanceFirst

#define _np1_red2CallProcedureIndexed addresses
#define _np2_red2CallProcedureIndexed calls
#define _np3_red2CallProcedureIndexed indexCount
#define _np4_red2CallProcedureIndexed instanceCount
#define _np5_red2CallProcedureIndexed indexFirst
#define _np6_red2CallProcedureIndexed vertexBase
#define _np7_red2CallProcedureIndexed instanceFirst

#define _np1_red2CallProcedureCompute addresses
#define _np2_red2CallProcedureCompute calls
#define _np3_red2CallProcedureCompute workgroupsCountX
#define _np4_red2CallProcedureCompute workgroupsCountY
#define _np5_red2CallProcedureCompute workgroupsCountZ

#define _np1_red2CallSetProcedure addresses
#define _np2_red2CallSetProcedure calls
#define _np3_red2CallSetProcedure procedureType
#define _np4_red2CallSetProcedure procedure

#define _np1_red2CallSetProcedureIndices addresses
#define _np2_red2CallSetProcedureIndices calls
#define _np3_red2CallSetProcedureIndices array
#define _np4_red2CallSetProcedureIndices setTo0
#define _np5_red2CallSetProcedureIndices setTo1

#define _np1_red2CallSetProcedureParametersVariables addresses
#define _np2_red2CallSetProcedureParametersVariables calls
#define _np3_red2CallSetProcedureParametersVariables procedureParameters
#define _np4_red2CallSetProcedureParametersVariables visibleToStages
#define _np5_red2CallSetProcedureParametersVariables variablesBytesFirst
#define _np6_red2CallSetProcedureParametersVariables dataBytesCount
#define _np7_red2CallSetProcedureParametersVariables data

#define _np1_red2CallSetProcedureParametersStructs addresses
#define _np2_red2CallSetProcedureParametersStructs calls
#define _np3_red2CallSetProcedureParametersStructs procedureType
#define _np4_red2CallSetProcedureParametersStructs procedureParameters
#define _np5_red2CallSetProcedureParametersStructs procedureParametersDeclarationStructsDeclarationsFirst
#define _np6_red2CallSetProcedureParametersStructs structsCount
#define _np7_red2CallSetProcedureParametersStructs structs
#define _np8_red2CallSetProcedureParametersStructs setTo0
#define _np9_red2CallSetProcedureParametersStructs setTo00

#define _np1_red2CallSetProcedureParametersHandles addresses
#define _np2_red2CallSetProcedureParametersHandles calls
#define _np3_red2CallSetProcedureParametersHandles procedureType
#define _np4_red2CallSetProcedureParametersHandles procedureParameters
#define _np5_red2CallSetProcedureParametersHandles procedureParametersDeclarationStructsDeclarationsCount
#define _np6_red2CallSetProcedureParametersHandles handlesCount
#define _np7_red2CallSetProcedureParametersHandles handles

#define _np1_red2CallSetDynamicStencilReference addresses
#define _np2_red2CallSetDynamicStencilReference calls
#define _np3_red2CallSetDynamicStencilReference face
#define _np4_red2CallSetDynamicStencilReference reference

#define _np1_red2CallSetDynamicBlendConstants addresses
#define _np2_red2CallSetDynamicBlendConstants calls
#define _np3_red2CallSetDynamicBlendConstants blendConstants

#define _np1_red2CallSetDynamicViewport addresses
#define _np2_red2CallSetDynamicViewport calls
#define _np3_red2CallSetDynamicViewport x
#define _np4_red2CallSetDynamicViewport y
#define _np5_red2CallSetDynamicViewport width
#define _np6_red2CallSetDynamicViewport height
#define _np7_red2CallSetDynamicViewport depthMin
#define _np8_red2CallSetDynamicViewport depthMax

#define _np1_red2CallSetDynamicScissor addresses
#define _np2_red2CallSetDynamicScissor calls
#define _np3_red2CallSetDynamicScissor x
#define _np4_red2CallSetDynamicScissor y
#define _np5_red2CallSetDynamicScissor width
#define _np6_red2CallSetDynamicScissor height

#define _np1_red2CallSetStructsMemory addresses
#define _np2_red2CallSetStructsMemory calls
#define _np3_red2CallSetStructsMemory structsMemory
#define _np4_red2CallSetStructsMemory structsMemorySamplers

#define _np1_red2CallSetProcedureParameters addresses
#define _np2_red2CallSetProcedureParameters calls
#define _np3_red2CallSetProcedureParameters procedureType
#define _np4_red2CallSetProcedureParameters procedureParameters

#define _np1_red2CallMark addresses
#define _np2_red2CallMark calls
#define _np3_red2CallMark mark

#define _np1_red2CallMarkSet addresses
#define _np2_red2CallMarkSet calls
#define _np3_red2CallMarkSet mark

#define _np1_red2CallMarkEnd addresses
#define _np2_red2CallMarkEnd calls

#define _np1_red2RedOnlyCallCopyImageToImage addresses
#define _np2_red2RedOnlyCallCopyImageToImage calls
#define _np3_red2RedOnlyCallCopyImageToImage imageR
#define _np4_red2RedOnlyCallCopyImageToImage setTo1
#define _np5_red2RedOnlyCallCopyImageToImage imageW
#define _np6_red2RedOnlyCallCopyImageToImage setTo01
#define _np7_red2RedOnlyCallCopyImageToImage rangesCount
#define _np8_red2RedOnlyCallCopyImageToImage ranges

#define _np1_red2RedOnlyCallCopyArrayToImage addresses
#define _np2_red2RedOnlyCallCopyArrayToImage calls
#define _np3_red2RedOnlyCallCopyArrayToImage arrayR
#define _np4_red2RedOnlyCallCopyArrayToImage imageW
#define _np5_red2RedOnlyCallCopyArrayToImage setTo1
#define _np6_red2RedOnlyCallCopyArrayToImage rangesCount
#define _np7_red2RedOnlyCallCopyArrayToImage ranges

#define _np1_red2RedOnlyCallCopyImageToArray addresses
#define _np2_red2RedOnlyCallCopyImageToArray calls
#define _np3_red2RedOnlyCallCopyImageToArray imageR
#define _np4_red2RedOnlyCallCopyImageToArray setTo1
#define _np5_red2RedOnlyCallCopyImageToArray arrayW
#define _np6_red2RedOnlyCallCopyImageToArray rangesCount
#define _np7_red2RedOnlyCallCopyImageToArray ranges

#define _np1_red2RedXOnlyCallCopyImageRegion calls
#define _np2_red2RedXOnlyCallCopyImageRegion copiesCount
#define _np3_red2RedXOnlyCallCopyImageRegion copies

#define _np1_red2RedOnlyCallDiscardImageAndSetState addresses
#define _np2_red2RedOnlyCallDiscardImageAndSetState calls
#define _np3_red2RedOnlyCallDiscardImageAndSetState context
#define _np4_red2RedOnlyCallDiscardImageAndSetState imagesCount
#define _np5_red2RedOnlyCallDiscardImageAndSetState images
#define _np6_red2RedOnlyCallDiscardImageAndSetState imagesAllParts
#define _np7_red2RedOnlyCallDiscardImageAndSetState state

#define _np1_red2CallBarrierUsagePresentToImage addresses
#define _np2_red2CallBarrierUsagePresentToImage calls
#define _np3_red2CallBarrierUsagePresentToImage context
#define _np4_red2CallBarrierUsagePresentToImage presentImage
#define _np5_red2CallBarrierUsagePresentToImage newAccessStages
#define _np6_red2CallBarrierUsagePresentToImage newAccess
#define _np7_red2CallBarrierUsagePresentToImage presentImageDiscardPreviousContent

#define _np1_red2CallBarrierUsageImageToPresent addresses
#define _np2_red2CallBarrierUsageImageToPresent calls
#define _np3_red2CallBarrierUsageImageToPresent context
#define _np4_red2CallBarrierUsageImageToPresent presentImage
#define _np5_red2CallBarrierUsageImageToPresent oldAccessStages
#define _np6_red2CallBarrierUsageImageToPresent oldAccess

#define _np1_red2CallBarrierOrderGlobalMemory addresses
#define _np2_red2CallBarrierOrderGlobalMemory calls

#define _np1_red2CallBarrierOrderResourceMemory addresses
#define _np2_red2CallBarrierOrderResourceMemory calls
#define _np3_red2CallBarrierOrderResourceMemory arraysCount
#define _np4_red2CallBarrierOrderResourceMemory arrays
#define _np5_red2CallBarrierOrderResourceMemory imagesCount
#define _np6_red2CallBarrierOrderResourceMemory images
#define _np7_red2CallBarrierOrderResourceMemory imagesAllParts

#define _np1_red2RedOnlyCallBarrierFinishCpuUpload addresses
#define _np2_red2RedOnlyCallBarrierFinishCpuUpload calls
#define _np3_red2RedOnlyCallBarrierFinishCpuUpload arraysCount
#define _np4_red2RedOnlyCallBarrierFinishCpuUpload arrays

#define _np1_red2RedOnlyCallBarrierFinishCpuReadback addresses
#define _np2_red2RedOnlyCallBarrierFinishCpuReadback calls
#define _np3_red2RedOnlyCallBarrierFinishCpuReadback arraysCount
#define _np4_red2RedOnlyCallBarrierFinishCpuReadback arrays

#define _np1_red2RedOnlyCallBarrierUsageAliasOrder addresses
#define _np2_red2RedOnlyCallBarrierUsageAliasOrder calls
#define _np3_red2RedOnlyCallBarrierUsageAliasOrder context
#define _np4_red2RedOnlyCallBarrierUsageAliasOrder arrayUsagesCount
#define _np5_red2RedOnlyCallBarrierUsageAliasOrder arrayUsages
#define _np6_red2RedOnlyCallBarrierUsageAliasOrder imageUsagesCount
#define _np7_red2RedOnlyCallBarrierUsageAliasOrder imageUsages
#define _np8_red2RedOnlyCallBarrierUsageAliasOrder dependencyByRegion

#define _np1_red2RedXOnlyCallBarrierUsageAliasOrder calls
#define _np2_red2RedXOnlyCallBarrierUsageAliasOrder barriersCount
#define _np3_red2RedXOnlyCallBarrierUsageAliasOrder barriers

#define _np1_red2RedXOnlyGetRedXAccessBitflagsFromRed access

#define _np1_red2RedXOnlyArrayGetMemoryTypeIndex array

#define _np1_red2RedXOnlyImageGetLevelsCount image

#define _np1_red2RedXOnlyImageGetLayersCount image

#define _np1_red2RedXOnlyArrayGetHandleResource array

#define _np1_red2RedXOnlyImageGetHandleResource image

#define _np1_red2CreateStream context2
#define _np2_red2CreateStream gpu
#define _np3_red2CreateStream handleName
#define _np4_red2CreateStream queueFamilyIndex
#define _np5_red2CreateStream signalGpuSignalOnQueue
#define _np6_red2CreateStream outStream
#define _np7_red2CreateStream outStatuses
#define _np8_red2CreateStream optionalFile
#define _np9_red2CreateStream optionalLine
#define _np10_red2CreateStream optionalUserData

#define _np1_red2DestroyStream context2
#define _np2_red2DestroyStream gpu
#define _np3_red2DestroyStream stream
#define _np4_red2DestroyStream optionalFile
#define _np5_red2DestroyStream optionalLine
#define _np6_red2DestroyStream optionalUserData

#define _np1_red2StreamGetCalls context2
#define _np2_red2StreamGetCalls gpu
#define _np3_red2StreamGetCalls stream
#define _np4_red2StreamGetCalls outCalls
#define _np5_red2StreamGetCalls outStatuses
#define _np6_red2StreamGetCalls optionalFile
#define _np7_red2StreamGetCalls optionalLine
#define _np8_red2StreamGetCalls optionalUserData

#define _np1_red2StreamSubmitCalls context2
#define _np2_red2StreamSubmitCalls gpu
#define _np3_red2StreamSubmitCalls stream
#define _np4_red2StreamSubmitCalls callsCount
#define _np5_red2StreamSubmitCalls calls
#define _np6_red2StreamSubmitCalls optionalFile
#define _np7_red2StreamSubmitCalls optionalLine
#define _np8_red2StreamSubmitCalls optionalUserData

#define _np1_red2StreamFlushToQueue context2
#define _np2_red2StreamFlushToQueue gpu
#define _np3_red2StreamFlushToQueue queue
#define _np4_red2StreamFlushToQueue highway
#define _np5_red2StreamFlushToQueue streamsCount
#define _np6_red2StreamFlushToQueue streams
#define _np7_red2StreamFlushToQueue outQueueSubmissionTicketArrayIndex
#define _np8_red2StreamFlushToQueue outQueueSubmissionTicket
#define _np9_red2StreamFlushToQueue outStatuses
#define _np10_red2StreamFlushToQueue optionalFile
#define _np11_red2StreamFlushToQueue optionalLine
#define _np12_red2StreamFlushToQueue optionalUserData

